### ISSUE TITLE
Clink not working in 1.3.18

### ISSUE THREAD

**Issue by Hraesvelg** [cmderdev/cmder#2546] opened 2021-05-20 11:27 UTC
### Purpose of the issue
- [X] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [ ] Question

### Version Information
Windows 10 lastest
cmder v1.3.18

### Description of the issue

hi all, just a message to specify that : 

Switch to @chrisant996 Clink v1.1.10 to fix Clink newer Windows 10 releases.

is a regression ! may be solved specific problem for one environnement but is not stable for many users... since the 1.3.16 impossible to launch clink, the init.bat block at this step and when i replace clink by the official version by mridgers for example when i launch the vagrant command the environnement not recognize powershell version.

**Comment by chrisant996** [comment] 2021-05-20 13:10
> Switch to @chrisant996 Clink v1.1.10 to fix Clink newer Windows 10 releases.
> 
> is a regression ! may be solved specific problem for one environnement but is not stable for many users... 

Can you explain more?
What are the ways it's a regression?
What are the instabilities?

There is one known instability in the Clink v1.1.45 pre-release that Cmder currently includes, but it's fixed in the official released versions of Clink v1.2 and higher.

> since the 1.3.16 impossible to launch clink, the init.bat block at this step and when i replace clink by the official version by mridgers for example when i launch the vagrant command the environnement not recognize powershell version.

Cmder 1.3.16 includes Clink 0.4.9, so replacing that with Clink 0.4.9 (the latest mridgers version) won't change anything.

Can you give more information about "when I launch the vagrant command the environment not recognize powershell version"?

**Comment by Hraesvelg** [comment] 2021-05-20 14:56
hi chrisant996

We have trying on three different computer with same configuration (w10 + cmder 1.3.18) and same result.
in the init.bat, i was able to target the command line who block :

"%CMDER_ROOT%\vendor\clink\clink_%clink_architecture%.exe" inject --quiet --profile "%CMDER_ROOT%\config" --scripts "%CMDER_ROOT%\vendor"

impossible to pass this command, when i launch clink.bat i have just a windows with prompt, no error, no message : 

![clink](https://user-images.githubusercontent.com/12531138/118997529-04602500-b989-11eb-82c9-ce981de987f6.png)

Sorry it's true, it's after the version 1.3.16 we have a problem. So, i have trying to custom cmder 1.3.18 with clink 0.4.9 : with this configuration, i can input command. Cmder "works" but not perfectly for example i have the error for vagrant (i think it's because the environnement is not correctly load because i have i custom cmder with old version of clink) :

![vagrant](https://user-images.githubusercontent.com/12531138/119000559-82253000-b98b-11eb-8841-54e0339742ff.png)

**Comment by chrisant996** [comment] 2021-05-20 15:50
I believe you and I'm not arguing with you.  I agree it's very frustrating when software doesn't work as expected.

My goal is to help get this tracked down and fixed.
Are you willing to help me do that?

**Can you please try copying the contents of [Clink v1.2.8](https://github.com/chrisant996/clink/releases/download/v1.2.8/clink.1.2.8.516b24.zip) into the `c:\cmder\vendor\clink` directory?**

Clink v1.2.8 is a release version, and it has some fixes that may help:
- v1.2.5 fixed where `clink inject --profile` writes logging information.  That will help with troubleshooting the problem, because the log file will be in the right place.
- v1.2.3 added failure reporting and logging when `clink inject` fails.  That will help with troubleshooting the problem, because more information will be reported in the log, and maybe also in the command prompt window.

If the problem still occurs after updating with Clink v1.2.8, then the next troubleshooting step will be to share the contents of the `c:\cmder\config\clink.log` file.  (But that won't help until after updating with v1.2.8, because v1.1.45 writes to an incorrect log file location.)

**Comment by Hraesvelg** [comment] 2021-05-20 16:03
The problem is already present with clink 1.2.8

the log file :
[clink.log](https://github.com/cmderdev/cmder/files/6517282/clink.log)

**Comment by chrisant996** [comment] 2021-05-20 17:09
This looks like antivirus is interfering.

The `clink inject` has injected a thread into cmd.exe, and received a "success" result from the OS.  So it waits for the thread to complete, which should be almost instantaneous.  But it never completes.

That strongly suggests that an antivirus program has blocked the call to inject a thread into cmd.exe.  When antivirus programs block things like this, they generally report success even though it failed, to try to trick what they assume is a malicious program.

While the `CreateRemoteThread()` API is sometimes abused by malicious programs, it is also sometimes used legitimately by benevolent programs such as Clink (it's the only way to inject Clink into cmd.exe).

Is there a way to tell your antivirus program to make an exception for Clink?  What antivirus program is being used?  If it's the built in Windows Defender then here's an article showing how to make an exception:  https://support.microsoft.com/en-us/windows/add-an-exclusion-to-windows-security-811816c0-4dfd-af4a-47e4-c301afe13b26.

**Comment by Hraesvelg** [comment] 2021-05-20 17:33
You are right ! my antivirus not showing message but after checking, when i launch clink, **cylance** intercept the program and reject his execution. I will look at to add exception for this. That said, the mridgers version of clink don't have the problem and i think he is based on the same function to manipulate cmd.exe ?!

Thanks !

**Comment by chrisant996** [comment] 2021-05-20 18:16
> You are right ! my antivirus not showing message but after checking, when i launch clink, **cylance** intercept the program and reject his execution. I will look at to add exception for this. 

That's good news. Let me know how it goes with adding an exception.

> That said, the mridgers version of clink don't have the problem and i think he is based on the same function to manipulate cmd.exe ?!

Yes. Antivirus programs are inexact, because they need to try to respond to unexpected/unknown threats, and they need to respond to variants of each threat.

Some antivirus programs use crowd-sourcing to add exceptions for benevolent programs. Sometimes the exceptions might even be for a specific version of a program.

Or sometimes signatures for threat detection are a little too "loose" and get false positives as a result. Then the antivirus program/team can adjust the signature to be more specific and avoid false positives. To be fair to them, that gets tricky because they also need to avoid false negatives.

Also, mridgers' versions have had lots of false positives with various antivirus programs. Even the v0.4.9 that's been around for so many years.

**Comment by Hraesvelg** [comment] 2021-05-20 18:32
In my home, i have retry the lastest release, the only problem is access to vagrant, i don't have specific antivirus and i have add exclusion for directory where is it cmder, i don't know if cmder is only the reason but :

at left : version 1.3.16, at right : 1.3.18 
![cmder_vagrant](https://user-images.githubusercontent.com/12531138/119030169-d5a67680-b9a9-11eb-819a-dc53c88a8974.png)

**Comment by chrisant996** [comment] 2021-05-20 21:20
See https://github.com/Maximus5/ConEmu/issues/2296

It's a known issue in ConEmu 210304.  Maximus doesn't know why yet.

**Comment by philgzl** [comment] 2021-05-25 14:28
Hi,

I have a similar issue. I get a `Unable to inject Clink` error message when I launch Cmder. My `clink.log` file is not quite the same as @Hraesvelg though, it has an extra `Failed to snapshot module state` line:

```
1e0c inject                    463 ---- 2021/05/25 16:13:15.950 -------------------------------------------------
1e0c inject                    464 Injecting Clink...
1e0c is_clink_present          245 Failed to snapshot module state.
1e0c inject_dll                203 Version: 1.2.8.516b24
1e0c inject_dll                204 Arch: x64
1e0c inject_dll                205 DLL: C:\Users\phigon\AppData\Local\Temp\clink\dll_cache\1.2.8.516b24_4e70eca6\clink_dll_x64.dll
1e0c inject_dll                207 Parent pid: 3572
1e0c check_dll_version         159 DLL version: 00010002 00080000
```

A month ago or so everything was working fine, and I don't feel like I touched anything. I tried downgrading to older versions but it's the same. I don't get any alert message by the antivirus provided by my organization (Cortex XDR Endpoint Protection), but I am also given close to zero option to monitor what it's doing nor add exceptions.

**Comment by chrisant996** [comment] 2021-05-25 16:26
> I have a similar issue. I get a `Unable to inject Clink` error message when I launch Cmder. My `clink.log` file is not quite the same as @Hraesvelg though, it has an extra `Failed to snapshot module state` line:
> 
> ```
> 1e0c inject                    463 ---- 2021/05/25 16:13:15.950 -------------------------------------------------
> 1e0c inject                    464 Injecting Clink...
> 1e0c is_clink_present          245 Failed to snapshot module state.
> ```

Unfortunately logging during inject wasn't reporting errors as actual errors, so the error code isn't included in the log.  I've fixed that for the next release, so that at least the log will include an error code indicating why the snapshot failed.  My guess is it will probably be 5 (Access is denied).  But whatever error code is happening, it seems very possible that it's caused by a false positive from anti-malware software.

> A month ago or so everything was working fine, and I don't feel like I touched anything. I tried downgrading to older versions but it's the same. I don't get any alert message by the antivirus provided by my organization (Cortex XDR Endpoint Protection), but I am also given close to zero option to monitor what it's doing nor add exceptions.

I'm sorry, that's so frustrating!  Unfortunately I can't do anything about it.  Clink has to inject itself into cmd.exe, and that's inherently something that can feel suspicious to anti-malware software.  There's no way around that.

**Comment by OfficerHalf** [comment] 2021-05-25 19:44
@Hraesvelg did you find a solution to this? My org uses cylance as well. IT is stingy with those exceptions...

**Comment by Hraesvelg** [comment] 2021-05-25 20:27
Hi @OfficerHalf while maximus not fix the origin problem. I work with the version 1.3.16, the only allow and usable for my utilisation

**Comment by chrisant996** [comment] 2021-05-25 23:18
@Hraesvelg and @OfficerHalf you can report directly to cylance that it is getting a false positive.  When antivirus software teams receive reports of false positives, then typically analyze the instance to confirm whether it's a false positive, and typically update whichever virus signatures were getting triggered so that they won't get triggered anymore.

What gets problematic is if they use a hash of the .exe file and/or .dll file to build in a version-specific exception.  Because that will only apply to one specific version, and has to keep getting updated.  On the other hand, signatures are constantly needing to get updated anyway to respond to virus mutations, and so there is always the possibility for false positives to recur later on.

**Closed** 2022-04-16 14:09 UTC
Labels: 👀 Awaiting Response
