### ISSUE TITLE
Cmder doesn't show lambda - just normal "prompt"

### ISSUE THREAD

**Issue by gabriellima** [cmderdev/cmder#2167] opened 2019-09-16 09:58 UTC
Hi there. Yesterday I first opened Cmder and everything was working.

After restarting the PC, I don't get that beautiful lambda sign anymore. It's just a "normal conemu prompt".

If it helps, I can't even use "keyboard shortcuts" like CTRL+L. Instead of clearing the log, it just inserts a `^L` sign

![image](https://user-images.githubusercontent.com/487779/64949310-47cacd80-d84f-11e9-9faa-f144430b6dd0.png)

**Comment by gabriellima** [comment] 2019-09-16 11:40
I'm in corporate network right now.

Out of nowhere, I had an idea to try using my personal WIFI before starting Cmder. Turns out that was the issue.

But, could anybody explain why Cmder needs to have an "open internet connection" in order to function correctly?

After it opened as supposed to, I finished it and logged back to my corporate network, and after reopening it it came back to "default not funny cmd.exe" again.

What's going on here?

**Comment by CollinChaffin** [comment] 2019-09-17 14:25
Yep, @gabriellima see https://github.com/cmderdev/cmder/issues/2166

Remove the "--nolog" (assuming you upgraded to latest build) as I pointed out in that issue and restart cmder and your cmd prompts return to normal.

**Comment by gabriellima** [comment] 2019-09-18 10:05
@CollinChaffin , thank you. I'm sorry, I'm running latest released version (v1.3.12.915) but can't seem to find any `nolog` statement on `cmder\vendor\init.bat` file.
I even downloaded a new zip file directly from github, in doubt that I may had already remove that statement, but couldn't find either.

Was it released?

Anyway, I think we can close this issue, at least for me, as I'm not seeing the issue anymore.

**Comment by daxgames** [comment] 2019-09-18 12:29
@gabriellima Cmder with clink --nolog has not been released.  Also I can't explain tour original ossue and Cmder does not require a network connection.

**Comment by CollinChaffin** [comment] 2019-09-18 13:36
Okay thanks @daxgames so obviously this is a one-off.  I have myself had instances where opening cmder with many tasks that then focuses on the last task opened, where my first few are cmd.exe based where I'll get no prompt but it's been rare.

**Comment by daxgames** [comment] 2019-09-19 23:09
@gabriellima you could Dd `-d` to the cmder task to print some debug statements on startup.  You can also run `cmder_diag` and share the output.  Please look at the data before you post it as it may contain sensitive data.

I doubt any of this will help though since as i said before cmder does not require any network connection.

**Comment by gabriellima** [comment] 2019-09-20 14:23
@daxgames , thank you. I've uploaded `cmder_d_output.txt` (output of `/d` on cmder init), and `cmder_diag_output` (output of `cmder_diag` command).

Also, I've already tried closing and reopening cmder several times, without success on `lambda sign`. If it's of any help, shortcuts like `CTRL+L` doesn't do as expected (call the `clear` command), as if "shortcuts" could not be attached to console. 

[cmder_d_output.txt](https://github.com/cmderdev/cmder/files/3636328/cmder_d_output.txt)
[cmder_diag_output.txt](https://github.com/cmderdev/cmder/files/3636329/cmder_diag_output.txt)

**Comment by daxgames** [comment] 2019-09-21 22:33
@gabriellima I see no obvious issues with your configuration but I can't explain the issues that you're having.   I think there is something possibly on your system that is causing the problem but I don't believe it's cmder.

It is very difficult to diagnose an issue that you can't reproduce so unless you can for providee some steps to reproduce it I'm closing the issue.   You can re open it when you can providethe  steps.

**Closed by daxgames** 2019-09-21 22:33 UTC

**Comment by gabriellima** [comment] 2019-09-23 09:32
dax, thank you. I'll keep investigating. It might have something to do with "Trend micro" AV, as everything in my corporate computer does.

**Comment by daxgames** [comment] 2020-01-05 22:06
@gabriellima @CollinChaffin Try [this](https://ci.appveyor.com/project/MartiUK/cmder/builds/29908645/artifacts)
