### ISSUE TITLE
Git checks for 'commits' every time a folder is changed?

### ISSUE THREAD

**Issue by informumar** [cmderdev/cmder#529] opened 2015-06-10 14:19 UTC
Every time, when 'cd' is done from one folder to another, git checks whether there are new commits in the folder and it takes a lot of time for me. Is it an issue? Can I somehow disable git check from cmder?

**Comment by Morten242** [comment] 2015-06-16 15:18
Assuming you're using powershell you can edit profile1.ps1 in the vendor folder.
Comment out `$gitStatus = $true` (should be around line 10) and it will stop looking for git folders.

I'm not sure how to do it in cmd.

**Comment by glucas** [comment] 2015-06-18 14:48
For a cmd shell, the git prompt magic is implemented with a lua script that registers a prompt hanlder with clink. 

If you don't want it I believe you can comment out the `clink.prompt.register_filter` lines toward the end of your `cmder/config/cmder.lua` file.

**Comment by Jayflux** [comment] 2016-01-12 00:08
for large projects (i dev on Servo on windows) this really is a nightmare, im talking almost a minute on every cd.

Is there any way of speeding this up or removing it from default setup?
Its making Cmder unusable.

**Comment by JanSchulz** [comment] 2016-01-12 08:12
@Jayflux Have you tried it with the latest development release? see here for installer: https://ci.appveyor.com/project/MartiUK/cmder/build/1.0.138-development/artifacts

I think it also makes sense to add a fast check in lua to disable it via a `config\user.lua` or `config\user_profile.bat` file. Not sure how to do that. Probably via a environment variable?

**Comment by DanielGGordon** [comment] 2016-01-12 14:30
I assume this problem is non-existent on git bash (that does not come with cmder)

**Comment by Jayflux** [comment] 2016-02-10 20:14
@JanSchulz Should i not be checking this against the latest pre-release? Which is https://github.com/cmderdev/cmder/releases/tag/v1.2.9 ?

Im not sure where that link you sent me fits in with the releases on github

**Comment by JanSchulz** [comment] 2016-02-10 21:45
Nope, the latest (unofficial) pre release is what you get when you follow the appveyor link. We are currently approaching 1.3 with a lot of changes...

**Comment by Jayflux** [comment] 2016-02-13 12:41
@JanSchulz I have downloaded the latest Cmder from https://ci.appveyor.com/project/MartiUK/cmder/build/1.0.177-development/artifacts I can confirm it is much faster with large git repos, no lag at all!

Thank you
When do you hope to have this release out?

**Comment by vladimir-kotikov** [comment] 2016-02-15 19:01
@JanSchulz, do you have an idea about what might be the cause of these lags? Something that was changed since 1.2.9

@Stanzilla, i think this is not related to `clink-completions`, since the git prompt is still handled by cmder.lua that is still a part of Cmder. Or am I missing something?

**Comment by Stanzilla** [comment] 2016-02-15 19:15
Nope, you're right.

**Comment by JanSchulz** [comment] 2016-02-15 20:26
@vladimir-kotikov Actually I suggested the latest build because something in the git check was changed and that fixed some slowness. But I've no clue what exactly that was or why it helped here.

**Comment by Jackbennett** [comment] 2016-05-26 15:13
From the sounds of it this is fixed in newer versions. I know the PS Side will be smarter about git in the prompt department.

If not please re-open or make a new issue.

**Closed by Jackbennett** 2016-05-26 15:13 UTC
