### ISSUE TITLE
shortcut not work in git-bash/mintty

### ISSUE THREAD

**Issue by eromoe** [cmderdev/cmder#1080] opened 2016-08-23 09:26 UTC
such as : `win` + `alt`\+ `left`, `win` + `alt` + `p` or `ctrl` + `alt` + `xxx` .

Worked in `cmd` mode.

**Comment by Jackbennett** [comment] 2017-01-25 12:23
duplicate of #1218

**Closed by Jackbennett** 2017-01-25 12:23 UTC
