### ISSUE TITLE
Error when try to access a fresh installed Laravel folder

### ISSUE THREAD

**Issue by marcelo2605** [cmderdev/cmder#687] opened 2015-10-28 19:35 UTC
After run composer to download Laravel 5, I try to access the folder and Cmder return the following error:

```
...gram Files\cmder/vendor/clink-completions/npm_prompt.lua:11: attempt to concatenate local 'package) nil valu
```

**Comment by Stanzilla** [comment] 2015-10-28 19:37
Dupe of https://github.com/cmderdev/cmder/issues/678

**Closed by Stanzilla** 2015-10-28 19:37 UTC
Labels: upstream: clink-completions
