### ISSUE TITLE
SSH Permission denied against certain clents

### ISSUE THREAD

**Issue by jonaswikstrom** [cmderdev/cmder#2076] opened 2019-04-06 11:03 UTC
### Purpose of the issue
- [x] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [ ] Question

### Version Information

ConEmu: 180626 preview
Cmnder: 1.3.11

Version	10.0.17763 Build 17763

### Description of the issue 
Certainly not a specific Cmnder issue but for a newbie like me. Trying to use the SSH client towards some of my Linuxclients/RRi's. Works like charm for some of them all RPi's (Raspian/Hassbian) but for my Ubuntu machines I always get Permission denied. Using Ubuntu terminal on Windows / Putty works out of the box.

Any hints?

**Comment by daxgames** [comment] 2019-04-06 12:53
@jonaswikstrom I am sorry I dont understand the issue.  Could you provide more detail or step by step reproduction?

**Comment by daxgames** [comment] 2019-05-11 12:10
Closing due to non reaponse.

**Closed by daxgames** 2019-05-11 12:10 UTC
