### ISSUE TITLE
Path variables in alias not expanding

### ISSUE THREAD

**Issue by yokuyuki** [cmderdev/cmder#759] opened 2015-12-08 06:34 UTC
Any environment variables in the alias file for cmd doesn't expand even though one of the default ones for history uses it.

```
λ history
cat: %CMDER_ROOT%\config\.history: No such file or directory
```

If you type it out though, it works:
```
λ cat %CMDER_ROOT%\config\.history
cd .ssh
cat id_rsa.pub
```

**Comment by glucas** [comment] 2015-12-09 20:28
This is a duplicate of #684.

**Closed** 2015-12-09 20:42 UTC
Labels: Duplicate
