### ISSUE TITLE
api-ms-win-crt-runtime-l1-1-0.dll error

### ISSUE THREAD

**Issue by aligoren** [cmderdev/cmder#501] opened 2015-05-22 18:43 UTC
api-ms-win-crt-runtime-l1-1-0.dll error. can not found be

**Edit: The solution has the following comment.**

Fixed. I tried @squimer solution.

https://github.com/bliker/cmder/issues/501#issuecomment-104749350

>I've solved my problem with Visual C++ Redistributable for Visual Studio 2015:

>For Windows 64-bit
>http://download.microsoft.com/download/0/4/1/041224F6-A7DC-486B-BD66->BCAAF74B6919/vc_redist.x64.exe

>For Windows 32-bit
>http://download.microsoft.com/download/0/4/1/041224F6-A7DC-486B-BD66-BCAAF74B6919/vc_redist.x86.exe

**Comment by atantillo** [comment] 2015-05-22 18:57
Have you tried installed MS Visual Studio Redist? 

http://www.microsoft.com/en-us/download/details.aspx?id=5555

**Comment by aligoren** [comment] 2015-05-22 19:16
Yes i tried. I've previously installed on my computer.

**Comment by atantillo** [comment] 2015-05-22 19:17
Have you tried both 2010 and 2007?

http://www.microsoft.com/en-us/download/details.aspx?id=29

**Comment by squimer** [comment] 2015-05-22 19:20
Same here :\

**Comment by aligoren** [comment] 2015-05-22 19:22
I tried 2010. I'm using Windows 7 32-bit.

**Comment by atantillo** [comment] 2015-05-22 19:25
Try installing the 2007 redis and see if that solves your issue.

**Comment by squimer** [comment] 2015-05-22 19:32
I solve my problem with Visual C++ Redistributable for Visual Studio 2015:

For Windows 64-bit
http://download.microsoft.com/download/0/4/1/041224F6-A7DC-486B-BD66-BCAAF74B6919/vc_redist.x64.exe

For Windows 32-bit
http://download.microsoft.com/download/0/4/1/041224F6-A7DC-486B-BD66-BCAAF74B6919/vc_redist.x86.exe

**Comment by aligoren** [comment] 2015-05-22 19:39
I solved the problem now. squimer gave in the link I downloaded the file I installed that solved the problem. cmder works. Maybe you can add the solution to the Readme file. Thanks.

**Comment by mormegil-cz** [comment] 2015-05-22 21:26
VS2015 is currently in RC, is it really a good idea to ask users to install pre-release versions of DLLs? I'd recommend reverting to VS2013 until VS2015 gets to RTM.

**Comment by atantillo** [comment] 2015-05-23 01:37
Huh, I didn't see that upgrade until now. I didn't have to upgrade my VS dist, but than again I'm running Windows 10 RC, and that probably comes packaged with that dist.

**Comment by matteocontrini** [comment] 2015-05-23 12:07
I had the same problem without VS 2015 installed. @squimer solution helped.

**Comment by mygoare** [comment] 2015-05-23 14:20
I am win7 32-bit, I met the same problem, thanks @squimer, my problem has been solved.

**Comment by LazyZhu** [comment] 2015-05-23 15:41
@MartiUK
Could you please rebuild with VS2013?

**Comment by Stanzilla** [comment] 2015-05-23 15:48
he already did, he's been testing (or so) it for a few days now.

**Comment by CooCooooo** [comment] 2015-05-24 03:44
well  I get the same problem ( vs2013 )

**Comment by LRPalacios** [comment] 2015-05-24 04:45
Same here without VS2015 on windows 8.1

**Comment by imsyuan** [comment] 2015-05-25 04:53
I solved the problem now. You need to finish windows update.
And download @squimer link.

**Comment by ouchxp** [comment] 2015-05-25 09:52
@imsyuan What do you mean "finish" windows update? Terminate the process? My computer is up to date, I tried install the file @squimer gives on two Win8.1 computer, but never succeed.

**Comment by LRPalacios** [comment] 2015-05-25 15:30
I can confirm that @squimer solution works on windows 8.1 while having VS2013

**Comment by paulo-lima** [comment] 2015-05-25 21:20
I've solved my problem with Visual C++ Redistributable for Visual Studio 2015 for Windows 64-bit as proposed by @squimer - running Windows 8.1

**Comment by ouchxp** [comment] 2015-05-25 21:31
@LRPalacios Thanks, I succesfully installed Visual C++ Redistributable for Visual Studio 2015 after I install Visual C++ Redistributable for 2010, 2012 and 2013.

**Comment by gregwebs** [comment] 2015-05-26 00:52
squimer's 64 bit link worked for me on Windows 7

**Comment by Djabx** [comment] 2015-05-26 17:22
@squimer solution helped

**Comment by IkerGimenez** [comment] 2015-05-26 17:40
I'm sure installing the runtime fixes the issue, but it breaks the portable factor of the program. Hope it's fixed soon...

**Comment by dserodio** [comment] 2015-06-01 16:20
I have this same problem on Windows Server 2008 and I agree with @IkerGimenez, this breaks the portability factor.

**Comment by marcusmalmberg** [comment] 2015-06-03 05:44
@squimer's solution (https://github.com/bliker/cmder/issues/501#issuecomment-104749350) fixes it, but as mentioned: it breaks the portability.

**Comment by murych** [comment] 2015-06-03 12:45
@squimer thanks for the solution!

**Comment by sealocal** [comment] 2015-06-03 19:32
The "Visual C++ Redistributable for Visual Studio" fails to install on my machine, so I looked for another solution.

I noticed that the README for the master branch of this repo states that the latest release is `v1.2`, and has a link to the release page.  However, `v1.2` is currently a pre-release.

I've opted for the latest release `v1.1.4.1`, found here: https://github.com/bliker/cmder/releases/tag/v1.1.4.1

**Comment by gugahoi** [comment] 2015-06-04 05:39
@sealocal's solution worked for me on W8, no extra DLL's needed.

**Comment by ArtiPanov** [comment] 2015-06-06 22:38
Спасибо! помогла установка Visual C++ Redistributable for Visual Studio 2015

**Comment by frederik256** [comment] 2015-06-08 09:14
Fresh win 8.1 Pro. No visual studio.  v1.2 full.   @squimer solution fixed the issue.

**Comment by donalmadden** [comment] 2015-06-08 14:49
Both the .7z & the .zip (full) failed for me ... @sealocal's solution worked fine though

**Comment by DoCode** [comment] 2015-06-09 07:18
Please revert the solution to vs2013!

**Comment by Saturate** [comment] 2015-06-10 11:36
Same issue for me, worked to install this: http://www.microsoft.com/en-us/download/details.aspx?id=46881

**Comment by gph** [comment] 2015-06-11 02:52
.7zip (v1.1.4.1) worked! thanks @sealocal

**Comment by babhishek21** [comment] 2015-06-14 20:44
Its extremely confusing when the main README.md states that the latest `release` is v1.2 and yet the v1.2 is marked `pre-release` and hence not fit for `release`.

**Comment by oblitum** [comment] 2015-06-15 02:42
Please, produce a release that doesn't depend on RC redistributables, this is not a good idea at all.

**Comment by binarywizard** [comment] 2015-06-18 03:30
Thank you! @squimer

**Comment by Gaohaoyang** [comment] 2015-06-18 08:00
Thx @squimer

**Comment by frankfuu** [comment] 2015-06-18 08:53
Wasn't able to install either 32 or 64 bit versions of the redist links provided by @squimer

Error log 

```
[0798:1768][2015-06-18T18:52:31]i301: Applying execute package: Windows81_x64, action: Install, path: C:\ProgramData\Package Cache\469A82B09E217DDCF849181A586DF1C97C0C5C85\packages\Patch\amd64\Windows8.1-KB2999226-x64.msu, arguments: '"C:\Windows\SysNative\wusa.exe" "C:\ProgramData\Package Cache\469A82B09E217DDCF849181A586DF1C97C0C5C85\packages\Patch\amd64\Windows8.1-KB2999226-x64.msu" /quiet /norestart'
[0798:1768][2015-06-18T18:52:32]e000: Error 0x80240017: Failed to execute MSU package.
[1968:13E0][2015-06-18T18:52:32]e000: Error 0x80240017: Failed to configure per-machine MSU package.
[1968:13E0][2015-06-18T18:52:32]i319: Applied execute package: Windows81_x64, result: 0x80240017, restart: None
[1968:13E0][2015-06-18T18:52:32]e000: Error 0x80240017: Failed to execute MSU package.
[0798:1768][2015-06-18T18:52:32]i372: Session end, registration key: SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\{e2495eb6-cca8-47aa-91ea-3410ca44d7b7}, resume: ARP, restart: None, disable resume: No
[0798:1768][2015-06-18T18:52:32]i371: Updating session, registration key: SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\{e2495eb6-cca8-47aa-91ea-3410ca44d7b7}, resume: ARP, restart initiated: No, disable resume: No
[1968:13E0][2015-06-18T18:52:32]i399: Apply complete, result: 0x80240017, restart: None, ba requested restart:  No
```

**Comment by hcuk94** [comment] 2015-06-18 20:51
Same issue for me. I wondered if it was anything to do with the fact I have Office 2016 Preview installed - seems to be a recent issue from my searching online. Either way, will try @squimer's fix. Thanks.

**Comment by berryman13** [comment] 2015-06-20 07:17
Apparently I have both those things already instlalled on my win7 machine. Both setups failed, x64 got to 99% before failing. I have VS2013 installed but not 2015......


No windows 10, No Office 2016 (huh?), and no VS2015.

**Comment by susanBuck** [comment] 2015-06-20 15:59
The extra .dlls also failed on installation for me (Windows 7). 

Work around was to d/l older version of Cmder from Aug 31:
https://github.com/bliker/cmder/releases/download/v1.1.4.1/cmder.zip

**Comment by eyp** [comment] 2015-06-23 16:24
Yes, 1.1.4.1 works fine, thank you. I'm not able to install anything because of lacking og administrative permissions, so I needed a true portable version like this one.

**Comment by thany** [comment] 2015-06-25 12:38
Wouldn't it be just as simple as including said dll in the portable package?... I don't believe an application cares very much where a required dll is located exactly.

**Comment by bjornregnell** [comment] 2015-07-02 12:51
Agree with thany!

**Comment by joaoeduardo** [comment] 2015-07-03 16:23
If you get error while the installation of Visual C++ Redistributable for Visual Studio 2015, update your system. Here, I installed SP1, and works.

**Comment by berryman13** [comment] 2015-07-03 17:54
Wnidwos 10 build 10147 (I know i'm updating to 10158 later on) -- no VS2015, 

bbut  Ihad .NET libraries, all the C++ objects for x86 and x64, up to 2013 anyways....This really needs that one DLL, it doesn't even come bundled with WIn10 x64.

**Comment by eyp** [comment] 2015-07-03 22:42
> If you get error while the installation of Visual C++ Redistributable for Visual Studio 2015 on Windows > 7, update your system. Here, I installed SP1, and works.

Some people like me don't have administration permissions, that's the reason we like a portable package which doesn't need priviledges to install anything... because we can't update any software in the usual way...

**Comment by sealocal** [comment] 2015-07-03 23:35
Exactly. I was in the same situation as @eyp.

**Comment by shakna-israel** [comment] 2015-07-05 11:43
Same as @frankfuu, here.

Windows 8.1, 64bit.

**Comment by attlas** [comment] 2015-07-07 19:36
@frankfuu @shakna-israel  try to install the vc_redist file again, choose repair...it worked for me

**Comment by oblitum** [comment] 2015-07-07 20:55
So many people complaining, is this supported yet?

**Comment by shakna-israel** [comment] 2015-07-08 03:39
@attlas - I don't get the choice to repair, as it never actually installs.

**Comment by isimmons** [comment] 2015-07-10 20:22
After installing the redist package I found the dll inside windows/system32 and just copied it to the root of cmder installation.

I think this is what needs to be included so users can stay portable and not need to install another runtime package.

I actually had to remove a bunch of different vcc redist and visual studio versions that had built up over time where I had to install them to get node, python, and various other things working. Then recently had issues where all these different versions were causing issues so had to remove all and install 2013 version. I don't want to have to install another version and end up with issues with other programs.

**Comment by babhishek21** [comment] 2015-07-11 06:30
@isimmons It may have worked, but removing all VCC redist versions before 2013 is definitely not the right way to go. Since each yearly update comes with new API features, other apps might not work. What I do is usually keep the latest redist of each yearly package. Yearly releases are backwards compatible and hence it makes sure that other stuff doesn't break.

Attached an image for good reference.
![image](https://cloud.githubusercontent.com/assets/8472087/8632698/5e9fdd74-27c4-11e5-9962-253d10b4b5de.png)

**Comment by isimmons** [comment] 2015-07-11 15:31
@babhishek21 Yes in theory that should work. My system used to look just like yours from 2005 up to 2013 because over time I had installed them all. Then one day I updated npm and node and the new node-gyp package could not compile native npm packages. Many others had the same issue and the solution was to remove all the old ones and then install visual studio 2013 express. I have no idea what the actual issue was or why that fixed it but that is the working solution many people had to do. 

But back to the topic of this issue, we should not need to install any of this because it kills the portability of cmder. Other dlls have been included with cmder to make it work without needing to install anything else so hopefully this dll will be included.

**Comment by babhishek21** [comment] 2015-07-11 16:54
@isimmons Of course, ideally the required dlls should be packaged (or at least included). I think the build was made on VS2015 Preview by accident using the Preview API.

**Comment by bethuel11** [comment] 2015-07-14 19:50
This happened to me on a new installed Win 8.1 Pro.
what I did is downloaded the 8.1 update from the microsoft website
for Win 8.1 x86 https://www.microsoft.com/en-us/download/details.aspx?id=42327
for Win 8.1 x64 https://www.microsoft.com/en-us/download/confirmation.aspx?id=42335

download and and install it. reboot your machine
reinstalled the Visual C++ 2015

CMDER works perfectly now. without errors

**Comment by vors** [comment] 2015-07-17 06:20
same issue, installing redistributed VS helped.

I think it should be handled more gracefully: dll could be **included** in the download or there could be a check with **prompt to install** dll from MS site, if not found.

**Comment by rebz** [comment] 2015-07-19 17:18
The solution provided by @squimer worked for me as well. Thanks!

**Comment by MBguous** [comment] 2015-07-21 17:50
thx @sealocal

**Comment by catdad** [comment] 2015-08-03 15:26
The REAME specifically says this:

```
It is designed to be totally self-contained with no external dependencies, that is makes it great for USB Sticks or Dropbox.
```

Doesn't that mean we should not be having these problems? I just downloaded v1.2 on my dev system (which has all sorts of Visual Studios and redistributables installed), and cannot run cmder.

**Comment by Stanzilla** [comment] 2015-08-04 03:57
If someone feels adventurous, you can test this https://github.com/Stanzilla/cmder/releases/tag/v1.2.1

It should work without any DLLs as is.

**Comment by gonzofish** [comment] 2015-08-07 13:19
@sealocal thanks for the solution!

**Comment by chartrandf** [comment] 2015-08-11 20:18
@Stanzilla Works fine me :)!

**Comment by javiercuadrado** [comment] 2015-08-13 04:22
Work for me on Win 7 x64.
These are the updated download links (x86 & x64)
https://www.microsoft.com/en-us/download/details.aspx?id=48145

**Comment by moonhawk74** [comment] 2015-08-14 13:16
Worked for me on Win7 x86 
@javiercuadrado: Thanks for the updated download links

**Comment by weiliank** [comment] 2015-08-23 04:45
https://www.microsoft.com/en-us/download/details.aspx?id=48145

this link works for me 

choose 32-bit or 64-bit then run the installer :)

**Comment by Vidhyadharantechdays** [comment] 2015-08-26 06:18
Yeah it works for me, Thanks  @weiliank , i am using windows 7 enterprise edition 64bit

**Comment by weiliank** [comment] 2015-08-26 06:30
@Vidhyadharantechdays welcome ! :)

**Comment by dmxt** [comment] 2015-09-03 02:53
@weiliank Link doesn't work anymore. Any alternative?

**Comment by rgriffogoes** [comment] 2015-09-05 19:08
@dmxt Just downloaded with provided link, and it worked (both download and cmder)!

**Comment by weiliank** [comment] 2015-09-06 02:28
@dmxt Hey there ! Sorry for the late reply :) so far i only approached this link and it works for me. Will try to source and post any other links if any.

**Comment by vexe** [comment] 2015-09-13 01:09
Is it just me? The VC++ Redistrib 2015 downloaders never start downloading (Firefox and Chrome)

**Comment by dmxt** [comment] 2015-09-13 04:12
@vexe Use internet explorer, that's how I solved that issue. Thanks Microsoft...

**Comment by Stanzilla** [comment] 2015-09-13 21:43
https://github.com/Stanzilla/cmder/releases/tag/1.2.4

**Comment by Saturate** [comment] 2015-09-14 11:29
@vexe it's a error on the MS site, they mix HTTPS and HTTP. Try to browse the site via http when downloading.

**Comment by UberGruber** [comment] 2015-09-23 17:06
Thanks a lot @Stanzilla for your fork, totally working now with no additional download and so on, nice job! :+1: 
Small off topic, if I pin on taskbar on win 8.1 when I click another icon is created next to it, anyone else?

**Comment by vukanac** [comment] 2015-09-24 12:38
Same issue on Win7 32b. I have noticed that Win 7 Service Pack 1 is missing.

**Comment by Hansel03** [comment] 2015-10-01 15:43
@squimer thanks for the solution......Excellent

**Comment by DanielGGordon** [comment] 2015-10-01 18:26
@UberGruber I think I had a similar thing. Have you looked at the 'Task Bar' menu under 'Main' in the settings? You might have the "show all consoles" button clicked or something

**Comment by w4r0** [comment] 2015-10-03 01:50
After tried to install the VC++ 2015 and failed, thanks to @sealocal, his solution is working.

**Comment by meerkat79** [comment] 2015-10-07 16:07
Just installed C++ Redist and that has copied the reuqired dll so cmder is loading now, thanks to clues above.

**Comment by UberGruber** [comment] 2015-10-07 18:53
@DanielGGordon  Thank you for your input, unfortunately the option you mention are unchecked, also this issue happens only in win 8.1, not in my other machine with Win 7.

**Comment by esteinborn** [comment] 2015-10-08 13:54
I have no problems when running 1.2.3 (https://github.com/Stanzilla/cmder/releases/tag/1.2.4) tag says 1.2.4 but is actually 1.2.3

**Comment by neOnSHiFT** [comment] 2015-10-12 11:15
I'm in x86 machine, I installed Visual C++ Redist 2013 and 2015 both x86 version but I that message still appear.
Do I have to install the x64 version too?

**Closed** 2015-10-12 11:21 UTC

**Comment by VenkatesanPrabhu** [comment] 2016-06-12 16:30
Good one Mr Aligoren..Thanks for the article..
Please visit my article about  api-ms-win-crt-runtime-l1-1.0.dll is missing

http://www.wikitechy.com/fix-error/how-to-fix-the-api-ms-win-crt-runtime-l1-1.0.dll-is-missing

**Comment by mmikeww** [comment] 2016-12-31 00:11
stackoverflow says that you cannot install the VC Redist package unless you ALSO have windows update KB2999226 installed:
https://stackoverflow.com/questions/33265663/api-ms-win-crt-runtime-l1-1-0-dll-is-missing-when-opening-microsoft-office-file

**Comment by CyaCyan** [comment] 2017-02-18 16:00
I have windows 7 and 64 bit and when I installed it its still not working any help???

**Comment by Helpp1** [comment] 2017-03-05 13:25
This is beacuse we miss this update https://support.microsoft.com/en-us/help/2999226/update-for-universal-c-runtime-in-windows This is Update for Universal C Runtime in Windows which can help you for sure just need to find your OS then download and instlal or also here i find good solutions This is for the Skype can’t start because api-ms-win-crt-runtime-l1-1-0.dll is missing
http://fanyit.com/problems-solutions-it/skype-cant-start-because-api-ms-win-crt-runtime-l1-1-0-dll-is-missing/
 but have good explanation for how to download and install this Universal upate for C Runtime and this is happend on more program becuase is missing this file but for all you can resolve with this update

**Comment by naitsirhc007** [comment] 2017-06-15 07:34
I found the answer on simply way...

Install Office 2016 64 bits.

That's ALL!!!

No one other method works

1 week in search...

**Comment by Trojan7z7VZX** [comment] 2018-01-13 14:20
Maybe you have some Windows updates missing! I searched and I found that you need the Windows update "KB2999226" and the Visual C++ Redistributable for Visual Studio 2015 or that you already have the Visual C++ Redistributable for Visual Studio 2015  but it failed to install so you need to reinstall it!

**Comment by bluebearkit** [comment] 2018-08-28 08:00
can anybody help me with this httpd.exe (Entry Point not found) of api-ms-win-crt-runtime-l1-1-0.dll?
i have uninstalled and installed visual 2015 but i always got the same error.

thanks in advance

**Comment by larrysurgey** [comment] 2019-03-02 12:50
You can fix the api-ms-win-crt-runtime-l1-1-0.dll error by updating your windows or by repairing VISUAL C++ REDISTRIBUTABLE FOR VISUAL STUDIO 2015.

Check out the guide here: https://www.intenseclick.com/api-ms-win-crt-runtime-l1-1-0-dll-is-missing-error/

Thanks,
Larry

**Comment by qzylalala** [comment] 2020-08-04 14:14
> This is beacuse we miss this update https://support.microsoft.com/en-us/help/2999226/update-for-universal-c-runtime-in-windows This is Update for Universal C Runtime in Windows which can help you for sure just need to find your OS then download and instlal or also here i find good solutions This is for the Skype can’t start because api-ms-win-crt-runtime-l1-1-0.dll is missing
> http://fanyit.com/problems-solutions-it/skype-cant-start-because-api-ms-win-crt-runtime-l1-1-0-dll-is-missing/
> but have good explanation for how to download and install this Universal upate for C Runtime and this is happend on more program becuase is missing this file but for all you can resolve with this update

thx.    It works for win7 x64

**Comment by wikidll** [comment] 2021-04-08 08:23
"For   more information,    
 Click here: https://wikidll.com/"   
   Thank you
