### ISSUE TITLE
Version 1.3.15.1010: The command line does not display the "λ" symbol

### ISSUE THREAD

**Issue by alexinea** [cmderdev/cmder#2347] opened 2020-07-12 08:48 UTC
![image](https://user-images.githubusercontent.com/980129/87242465-701b5c80-c45f-11ea-8301-91d5e366edb2.png)

My configuration in `init.bat` is:

```
@prompt $E[1;32;40m$P$S{git}{hg}$S$_$E[1;30;40m{lamb}$S$E[0m
```

My Tasks startup commands is:

```
cmd /k ""%ConEmuDir%\..\init.bat" -new_console:d:%USERPROFILE% "
```

I can't get the effect like in the screenshot of cmder.net.

Is there something wrong with my configuration?

**Comment by alexinea** [comment] 2020-07-12 09:05
I refer to #2166 and #2167. I didn't find `--nolog` under `init.bat`.

**Comment by daxgames** [comment] 2020-07-12 11:18
@alexinea did you edit `init.bat` to add some custom prompt config?  If so you shouldn't ever edit anything inside the vendor folder because every thing in that folder is overwritten on updates.

Custom prompt config should be added to a `%cmder_root%\config\*.lua file` and be written in lua.

**Comment by alexinea** [comment] 2020-07-12 13:24
Thank you very much @daxgames for your reply.

I only added one line of code:

```
@prompt $E[1;32;40m$P$S{git}{hg}$S$_$E[1;30;40m{lamb}$S$E[0m
```

I added this line of code (which used to appear in the old version of cmder) to make my cmder interface color.

Now after deleting this line of code, my colored text and the "λ" symbol are gone.

![image](https://user-images.githubusercontent.com/980129/87247240-2fced500-c485-11ea-9b47-b2227d1deaea.png)

And in the git folder, you can not prompt git branch information. (In previous versions of cmder there was no such problem.)

Even if the pure version of cmder-mini is downloaded from cmder.net, it will be different from the following picture after startup:

![image](https://user-images.githubusercontent.com/980129/87247292-86d4aa00-c485-11ea-9110-31d13262358d.png)

Am I missing a lot of caring information? Is it because of different versions?

**Comment by daxgames** [comment] 2020-07-12 14:39
The screenshot you refer to is VERY old.  I am running the current version of Cmder on Microsoft Windows [Version 10.0.19041.329] and the prompt looks like:

![image](https://user-images.githubusercontent.com/7318053/87249238-e3a37680-c42b-11ea-9996-c2ef64cdd332.png)


The line of code may have worked, but I doubt it, in a Cmder version from many years ago but would not work in the `init.bat` because it depends on clink and lua in any of the versions I have been associated with and that is at least the last 10-12 releases.

The clink output at the top is odd and should not be seen.  Do you have clink installed separately?

What version of Windows are you running please provide output of `ver` command.  There is an open issue that `clink` is not compatible with the latest Windows Insider version of Windows and we have no control over that.  See: #2341 and mridgers/clink#543

**Comment by alexinea** [comment] 2020-07-12 14:50
Yes, I installed clink separately.
My OS is Windows 10 Insider 20161.

After I uninstalled clink, the information about clink at the top when cmder started was no longer displayed. The picture below is the information I got after uninstalling clink.

![image](https://user-images.githubusercontent.com/980129/87249446-b7224580-c491-11ea-9d91-170a536c1d16.png)

**Comment by daxgames** [comment] 2020-07-12 16:06
You are experiencing https://github.com/mridgers/clink/issues/543.  Nothing I can do to help.

You might want to contribute to the referenced bug report.

**Comment by daxgames** [comment] 2020-07-12 16:07
Duplicate of #2341

**Closed by daxgames** 2020-07-12 16:07 UTC
Labels: 👆 clink

**Comment by nikitalita** [comment] 2020-10-03 01:30
Well, if nothing can be done about this, then cmder is going to be broken and useless when these changes in Insider start rolling to Windows stable.

**Comment by daxgames** [comment] 2020-10-03 02:18
@chrisant996 is actively working on a fork of [Clink 1.x.x](https://github.com/chrisant996/clink).  Hopefully he can address this.

**Comment by nikitalita** [comment] 2020-10-03 03:29
@daxgames already found the issue: https://github.com/mridgers/clink/issues/543#issuecomment-703037833

Patched version: https://github.com/nikitalita/clink/tree/v0.4.9-insider-fix

re: @chrisant996  https://github.com/chrisant996/clink/blob/master/clink/process/src/hook.cpp#L141

**Comment by kamenminkov** [comment] 2020-10-26 10:41
Wow, so nice to be able to use cmder again. Thank you for the workaround!

**Comment by chrisant996** [comment] 2020-10-26 17:22
> It's a bit slow at first launch (like it was before), hopefully the 1.x.x improves on that.

Clink 1.x installed separately, started by itself -- starts almost instantly on my machine.
Clink 1.x installed separately, started inside Cmder -- starts almost instantly on my machine.
Clink 0.4.9 installed with Cmder -- starts slowly on my machine.

That suggests the slowness is related to how Cmder integrates with Clink.  As I get Clink 1.x nearer to release, I'll profile the startup and see if there are inefficiencies in Clink itself, and see if there are any suggestions I can offer to the Cmder team for how to make Clink startup faster.

There are enough changes in Clink 1.x that it's unlikely to be a simple drop-in replacement; lua scripts will need to be updated, but it should be fairly straightforward.

**Comment by kamenminkov** [comment] 2020-10-27 08:54
Cool, looking forward to that!
