### ISSUE TITLE
Buffer History

### ISSUE THREAD

**Issue by PranshuVinayak** [cmderdev/cmder#2349] opened 2020-07-15 02:21 UTC
Hi, I just had a question about cmder. When i use a text editor like nano to open a file and then exit out of it, the previous outputs on the console are gone and it's basically blank. Is there any option i can select to keep viewing all those previous outputs? 
Thanks

**Comment by daxgames** [comment] 2020-07-15 02:59
I doubt it is cmder doing anything.  Another user complained about `vim` doing the same thing in cmder and it turned out to be a setting in `vim` to avoid clearing the screen on exit.

**Comment by daxgames** [comment] 2020-07-21 11:14
@PranshuVinayak

**Comment by PranshuVinayak** [comment] 2020-07-21 15:20
Thanks @daxgames, i did check the nano and vim settings but couldn't find the specific setting that could correct the issue, if you know about that please share.
Thanks

**Comment by daxgames** [comment] 2020-07-21 23:24
Add to `~/.vimrc`:

```
:set t_te=
```

**Comment by PranshuVinayak** [comment] 2020-07-22 00:35
This seems to show the file buffer that was just opened, but i was actually asking about the buffer for the previous console outputs.
Can you tell me the setting for that?

**Comment by daxgames** [comment] 2020-07-22 00:38
That is the setting that prevents vim from clearing the screen when exiting a file.  You can look up what it does on Google.

This is not a Cmder issue it is a user config issue.

**Comment by PranshuVinayak** [comment] 2020-07-22 00:41
Alright, but if it is a user config issue, then shouldn't i be experiencing the same thing with cmd or powershell too? which i don't.

**Comment by daxgames** [comment] 2020-07-22 00:53
Cmder default shell is `cmd.exe`.

What shell are you using?

**Comment by daxgames** [comment] 2020-07-22 00:57
Here is a screenshot I opened Cmder.  I typed `vi vendor\init.bat` and exited `vi`.  Notice the screen history before entering vi is still there.

![image](https://user-images.githubusercontent.com/7318053/88121780-ce99b680-cb94-11ea-86cb-4fc4f2495adf.png)

**Comment by PranshuVinayak** [comment] 2020-07-22 01:10
Hmm, I realize now that i forgot to mention this problem occurs only when i open something on a remote machine using ssh. Never Really tried on the local file system before, but yes it works well there. Any thoughts on the remote machine issue?

**Comment by daxgames** [comment] 2020-07-22 01:13
Did you configure the `~/.vimrc` using the setting I recommended on the remote machine?

**Comment by PranshuVinayak** [comment] 2020-07-22 01:16
Yes, I did. I created the **.vimrc** file as it didn't exist and it did something, like i mentioned above, just not what i wanted.

**Comment by PranshuVinayak** [comment] 2020-07-22 01:16
And one unrelated question, how are you able to get the relative path like **~\Cmder**, from the ScreenShot? How can i change to that from the Absolute path that windows shows?

**Comment by daxgames** [comment] 2020-07-22 01:20
I just ssh'd to a Windows host I have and had no issue.  I have no other type of host I can say to right now to test.  

Regarding the unrelated question see #2348

**Comment by PranshuVinayak** [comment] 2020-07-22 01:20
> 
> 
> Cmder default shell is `cmd.exe`.
> 
> What shell are you using?

The default, cmd.exe

**Comment by PranshuVinayak** [comment] 2020-07-22 01:23
> 
> 
> I just ssh'd to a Windows host I have and had no issue. I have no other type of host I can say to right now to test.
>
Can i provide you access to a linux host for that?

**Comment by PranshuVinayak** [comment] 2020-07-22 01:24
> Regarding the unrelated question see #2348

Thanks

**Comment by daxgames** [comment] 2020-08-28 12:26
I will see if I can figure out what is going on.  I can tet it with WSL 2.

**Comment by GittCatt** [comment] 2020-09-14 15:26
If that helps with anything, I'm having the same issue with my own full-screen Python application. In plain cmd, everything works fine and after exiting, I "return to previous screen", meaning: I have all my commands history. In cmder, however, the screen gets blank.

**Comment by tjallingran** [comment] 2020-09-15 09:01
I have the same issue with cmder, using the bundled git bash as terminal. The task is: `cmd /c ""%ConEmuDir%\..\git-for-windows\bin\sh" --login -i -new_console:d:C:\path\to\repo"`. I've set this task as the startup task.

Curiously, it only seems to happen on the first tab, i.e. the one that opens when starting Cmder. When I open a new tab (with the same task), the problem does not occur.

**Comment by rakib-hasan** [comment] 2020-10-18 04:27
Hi @daxgames , 
I see the same issue with both vi and nano when ssh'd to an Ubuntu system (tried both 16.04 and 20.04). NOTE: If I open cmder with startup command as "{bash::bash}", it works perfectly fine. The issue occurs when using "{cmd::Cmder}". Hope this extra information helps.

**Comment by rakib-hasan** [comment] 2020-10-19 09:31
@daxgames @PranshuVinayak @GittCatt , 
I think I found a workaround. Changing the startup command for the cmder task "{cmd::Cmder}" to the following seems to fix the issue:

`cmd /k ""%ConEmuDir%\..\init.bat" /nix_tools 2"`

NOTE: I just added the /nix_tools 2 option. You can read the [README.md](https://github.com/cmderdev/cmder/blob/master/README.md) to find out what it does. I hope this helps you and others who are having the same issue.
@daxgames Since this seems like a workaround, I hope this helps you narrow down the root cause of the issue.

**Comment by daxgames** [comment] 2020-10-19 12:44
It's probably the `ssh.exe` that comes with windows causing the issue.  `/nix_tools 2` changes the path so that `ssh.exe` is used from Git for Windows instead of the one from the Windows folder.

**Comment by rakib-hasan** [comment] 2020-10-19 21:33
Thanks @daxgames for the response. That is the puzzling part though. If it is related to the ssh.exe from Windows folder, the issue would be happening when ssh-ing directly from cmd.exe or powershell.exe as well, right? But it works fine there. There must be something incompatible with cmder and windows' ssh.exe .

**Comment by FavonianKong** [comment] 2020-10-20 01:12
> I have the same issue with cmder, using the bundled git bash as terminal. My git bash task is `cmd /c ""%ConEmuDir%\..\git-for-windows\bin\sh" --login -i -new_console:d:C:\path\to\repo"`. I've set this task as the startup task. The problem occurs after editing local files or git commit messages using vim, so it's not (just) remote files for me.
> 
> ~Curiously, it only seems to happen on the first tab, i.e. the one that opens when starting Cmder.~ It only happens after having the tab open for a while. When I open a new tab (with the same task), the problem does not occur at first.
> 
> Cmder version is 191012 preview.

I get the same phenomenon below: 
> It only happens after having the tab open for a while. When I open a new tab (with the same task), the problem does not occur at first. 

It seems that the bufferpool for the tab is used up，but not cleaned up in time :(

**Comment by tjallingran** [comment] 2020-11-23 12:59
The issue [occurs for me](https://github.com/cmderdev/cmder/issues/2349#issuecomment-692575920) in the bundled git bash. In those bash shells, utilities like `ssh` and `vim` already are the ones in the bundled git for windows.

I (don't) ssh into anything myself though, so I typically only see the issue after closing vim. My git repositories do push and pull via ssh, so I indirectly do use ssh (and run `ssh-agent` in the background).

**Comment by daxgames** [comment] 2020-12-23 11:47
@rakib-hasan more likely something incompatible between Windows ssh.exe and ConEmu.  ConEmu is a completely separate project redistributed Cmders GUI/Terminal Emulator.

**Comment by daxgames** [comment] 2020-12-23 11:51
Appears to be related to the ConEmu bundled version.

See: https://github.com/cmderdev/cmder/issues/2405#issuecomment-728666360

**Closed by daxgames** 2020-12-23 11:51 UTC
