### ISSUE TITLE
Cant get it working on windows xp

### ISSUE THREAD

**Issue by cupcakehunter** [cmderdev/cmder#598] opened 2015-08-18 18:48 UTC
Hey 

I am trying to get this working but it looks like mission impossible. When run the .exe file I get this error 

"The procedure entry point RegDeleteTreeW could not be located in the dynamic link library ADVAPI32.dll"

A bit of google search and I found this https://github.com/bliker/cmder/issues/161. Followed the instructions and downloaded & overwritten the exe file. Now I am getting and error for missing msvcp120.dll. I can see there is msvcp140.dll but not 120 so I found a msvcp.120.dll file and moved into the folder. still got the same error. Dont know what else to do so please help me guys

**Comment by sqrt** [comment] 2015-08-21 06:37
Just FYI: End-User Support for Windows XP [ended in April 2014](http://support.microsoft.com/lifecycle/search/default.aspx?alpha=Windows+XP), making it essentially hazardous to run it on a box connected to the internet.
With many applications ending support as well, you're probably best off upgrading to a current, supported version.

**Comment by Stanzilla** [comment] 2015-08-21 06:41
Dupe of https://github.com/bliker/cmder/issues/579 also see this issue for possible solution.

**Closed** 2015-10-12 11:43 UTC

**Comment by DRSDavidSoft** [comment] 2018-09-03 19:56
#1707 – Drop Windows XP support.

**Comment by 0x8008** [comment] 2025-02-08 16:31
> Just FYI: End-User Support for Windows XP [ended in April 2014](http://support.microsoft.com/lifecycle/search/default.aspx?alpha=Windows+XP), making it essentially hazardous to run it on a box connected to the internet. With many applications ending support as well, you're probably best off upgrading to a current, supported version.

Almost 10 years later and I still don't see the "hazards" mentioned
