### ISSUE TITLE
Path issues on startup

### ISSUE THREAD

**Issue by wallacewinfrey** [cmderdev/cmder#487] opened 2015-05-18 16:27 UTC
Executing Cmder 1.2 (Windows 7SP1) results in the following message:
```
PS C:\Windows\system32> C:\Users\wwinfrey\Applications\cmder\vendor\profile.ps1
Join-Path : Cannot bind argument to parameter 'Path' because it is null.
At C:\Users\wwinfrey\Applications\cmder\vendor\profile.ps1:2 char:29
+ $CmderModulePath = Join-path <<<<  $PSScriptRoot "psmodules/"
    + CategoryInfo          : InvalidData: (:) [Join-Path], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Microsoft.PowerShell.Commands.JoinPathCommand
 
WARNING: Missing git support, install posh-git with 'Install-Module posh-git' and restart cmder
```

**Comment by DiglidiDudeNG** [comment] 2015-05-18 17:07
Got the exact same problem after using `Set-ExecutionPolicy -ExecutionPolicy Bypass` to fix issue #483.

I have the feeling that this shouldn't have been released as a stable build yet. A development/beta branch could've made sure it's not confusing and/or unusable as a released build.

**Comment by saghul** [comment] 2015-05-19 09:12
Running into the same issue here, any idea on how to workaround it?

**Comment by MartiUK** [comment] 2015-05-19 12:05
The issue is that PowerShell 2 and below doesn't support $PSScriptRoot, I'm working on something that should let those with PS2 to work, though if you don't want to wait, install PowerShell 3 or above.

**Comment by MartiUK** [comment] 2015-05-19 14:50
c15e29ecb30e450c295f08651f4446fc026ea2a2 Should fix this.

@Jackbennett

**Comment by Jackbennett** [comment] 2015-05-19 15:08
Very neat Marti. I found the [bug report for $PSScriptRoot](https://connect.microsoft.com/PowerShell/feedback/details/522951/psscriptroot-only-works-with-modules) so I'm seing how moving our PS code into a (airquotes) proper "cmder" module will work out.

**Comment by wallacewinfrey** [comment] 2015-05-21 20:16
Upgrading my PowerShell version from 2.0 to 4.0 fixed this.

**Comment by yogelover** [comment] 2015-07-16 02:09
MartiUK solves the problem

**Closed** 2015-10-12 11:46 UTC
Labels: bug, easy pick, ready
