### ISSUE TITLE
CJK: Cursor is 1 space left to its correct position

### ISSUE THREAD

**Issue by niaodan2b** [cmderdev/cmder#2808] opened 2022-12-23 06:15 UTC
### Version Information

```markdown
Cmder version: 1.3.20.151
Operating system: Win11 22H2
```

### Cmder Edition

Cmder Mini

### Description of the issue

After pressing backspace or left arrow, the cursor position is 1 space left to its correct position, as the screenshot shows.
All settings are default.
I've tested ConEmu, doesn't have this problem.

![](https://i.imgur.com/SOmsvKY.gif)

### Checklist

- [X] I have read the documentation.
- [X] I have searched for similar issues and found none that describe my issue.
- [X] I have reproduced the issue on the latest version of Cmder.
- [X] I am certain my issues are not related to ConEmu, Clink, or other third-party tools that Cmder uses.

**Comment by chrisant996** [comment] 2022-12-24 21:56
Duplicate of #2774.

This is not a Clink bug, nor a Cmder bug, nor a ConEmu bug.

CJK defines a range of characters ambiguously, and it includes the lambda `λ` character -- for monospace fonts they can be 1 cell width, or 2 cells wide.  Depending on the font, the version of the OS, the Active Code Page, and the terminal program being used, the lambda character may display with a width different than expected.

The simplest solution is to run `chcp 65001` to make cmd.exe use UTF8.

**Comment by niaodan2b** [comment] 2022-12-25 08:10
Thanks for the info !
I don't know where to run this `chcp 65001`, I just edited config/cmder_prompt_config.lua to change the λ for $, and problem solved.

**Closed** 2022-12-25 12:53 UTC
Labels: 📖 Documentation, 💬 Type: Guide

**Comment by chrisant996** [comment] 2023-01-12 03:29
Clink v1.4.8 looks like it may have solved the width problems with the lambda character in the prompt.

**Comment by z-huabao** [comment] 2023-06-02 06:56
I change the startup task from {cmd:Cmder} to {bash:bash} or other shell, would not show this problem

**Comment by chrisant996** [comment] 2023-06-02 08:27
> I change the startup task from {cmd:Cmder} to {bash:bash} or other shell, would not show this problem

If a shell shows a lambda (`λ`) in the prompt, then the shell will have some variation of this problem, unless you change the codepage to UTF-8.  It is because of a mismatch in the OS when using codepage 932, 936, 949, or 950.  Different shells will encounter problems after different actions, but all of them will experience the problem under some conditions.

Here are two ways you can solve the problem:
1. Use the ConEmu Startup Environment settings page to add a line to run `chcp 65001`.  Refer to the [Startup Environment settings page](https://conemu.github.io/en/Settings.html#Environment) documentation for more info on configuring ConEmu.
2. You can [Change the Prompt Symbol](https://github.com/cmderdev/cmder/wiki/Customization#prompt-symbol).
