### ISSUE TITLE
Resizing adds new lines

### ISSUE THREAD

**Issue by HrvatJosip** [cmderdev/cmder#789] opened 2016-01-06 20:05 UTC
Seems like re-sizing the window adds new lines. Not too much of an issue but it is annoying at times. I'm on windows 10.
-Before Resizing
![before_resize](https://cloud.githubusercontent.com/assets/10729527/12153197/a79c60b6-b486-11e5-8120-8ba7cbae53fd.JPG)

-After Maximize
![after_maximize](https://cloud.githubusercontent.com/assets/10729527/12153208/b76ebb1a-b486-11e5-9f19-27fd1aec0ca4.JPG)

-After Restore Down
![after_restore_down](https://cloud.githubusercontent.com/assets/10729527/12153216/c4ab81a0-b486-11e5-857f-0d7f16b97e65.JPG)

-After HorizontalResize
![after_horizontal_resize](https://cloud.githubusercontent.com/assets/10729527/12153229/d36d41ba-b486-11e5-96b2-b1966622a1fc.JPG)

**Comment by vladimir-kotikov** [comment] 2016-01-06 21:33
Dupe of #753 and #689 and was fixed already in clink@0.4.6 (see https://github.com/mridgers/clink/issues/352)

**Closed** 2016-01-07 09:50 UTC

**Comment by aalvarado** [comment] 2016-01-17 11:48
fwiw I have the latest and does not have clink 0.4.6, I just had to download the portable clink and replace the one in vendor and now it works! thanks!
