### ISSUE TITLE
[Feature request] Update "Version" file to v1.3.21

### ISSUE THREAD

**Issue by snakecase** [cmderdev/cmder#2862] opened 2023-07-23 18:48 UTC
### Suggestion

The [latest](https://github.com/cmderdev/cmder/releases/tag/v1.3.21) 1.3.21 release still has `Version 1.3.20.151` file in both .7z and .zip archives.

### Checklist

- [X] I have read the documentation and made sure this feature doesn't already exist.
- [X] I have searched for similar issues and found none that describe my feature request.

**Comment by chrisant996** [comment] 2023-07-23 19:46
Looks like this is a duplicate of #2801?

That issue is closed, and it sounds like the plan is to leave the version info wrong until the next release of Cmder.

**Closed** 2023-07-24 10:48 UTC
Labels: 🛠 Type: Feature Request

**Comment by chrisant996** [comment] 2023-07-24 15:59
But why not update the version in the meantime? Version numbers matter.

**Comment by DRSDavidSoft** [comment] 2023-07-24 22:36
Good catch! @chrisant996 @snakecase 

Could you please take a look at the follow-up in the original issue?

https://github.com/cmderdev/cmder/issues/2818#issuecomment-1648709904
