### ISSUE TITLE
it doesn't like Docker

### ISSUE THREAD

**Issue by hmny** [cmderdev/cmder#631] opened 2015-09-09 19:13 UTC
if you install Docker on Windows, because of the Git that is installed along Docker, you'll lose all bash commands on Cmder:

`C:\Users\hmn
λ ls
'ls' is not recognized as an internal or external command,
operable program or batch file.`

**Comment by JanSchulz** [comment] 2015-09-09 19:21
which version of git is installed next to it (I don't have docker installed)? If it is Git for Windows 2.x, then this is a duplicate of https://github.com/cmderdev/cmder/issues/610#issuecomment-134669653

**Comment by hmny** [comment] 2015-09-10 15:18
Yes it seems that's the same problem.

**Closed** 2015-09-10 15:19 UTC
