### ISSUE TITLE
Problems using tmux on Host-side ? 

### ISSUE THREAD

**Issue by Dod9er** [cmderdev/cmder#1160] opened 2016-11-14 13:18 UTC
Hi, when I ssh to a remote-box (e.g. Ubuntu or CentOS) I use often tmux or byobu-tmux for session-handling, multiwindow etc.. Unfortunately, this easily brakes my terminal-view as in my screenshot. This is easily reproducable with tmux, but also happens with other terminal-output as soon as it gets somewhat fancy. Same doesn´t happen in putty.
Anyone experiencing the same issues ? 
![cmder](https://cloud.githubusercontent.com/assets/10465878/20266177/4657ede4-aa75-11e6-9e36-f41d78d44d43.png)

**Comment by jaypatel384** [comment] 2017-02-15 18:50
Hi, I use tmux over cmder as well and I've been facing these same issues. It's the only problem I've encountered so far on what is otherwise an amazing terminal for windows.

**Comment by Svenskunganka** [comment] 2017-03-13 02:44
I've got the same exact issue. Has the former commenters found a temporary workaround? For now I've settled with using PuTTY, but I miss using Cmder.

ConEmu's maintainer stresses it is not a bug with ConEmu in Maximus5/ConEmu#590 but rather the downstream terminals. At the same time, this issue is tagged with `upstream: ConEmu` and I don't see this issue being resolved with both projects pointing at eachother. Is there anything I can do to help pinpoint and identify the bug?

**Comment by olegstepura** [comment] 2017-03-20 13:40
Looks like preview build really solves this. I came here googling why tmux's status line is jumping up.

**Comment by Svenskunganka** [comment] 2017-03-20 15:05
Yes it seems to have fixed it, but at the same time I experienced some weird behaviour with colors & character encoding, especially with Vim. It was solved by running `tmux -u -2`. It has to be ran for all tmux commands, like `tmux attach -u -2`. To read what these parameters does, `man tmux`.

**Comment by HenryGessau** [comment] 2017-03-27 02:55
I have the latest preview build (170316) and I still have the problem. When I ssh to a server with byobu (tmux) enabled, the screen continuously scrolls. It should be updating byobu's status bar in place, not scrolling.

**Comment by noreplied** [comment] 2017-04-27 08:50
I am having the same issue as well. Just wondering are you guys able to scroll up for the buffer in tmux?

**Comment by rteshnizi** [comment] 2017-07-24 17:42
cmder has an issue with updating a line when using tmux. An easy way to reproduce this for example is to run yarn in a cmder session without tmux and in a session with tmux and see progress bars.

I have attached a screenshot to show it is still not fixed with the preview build of ConEmu.

![image](https://user-images.githubusercontent.com/1209547/28536466-504145f8-706d-11e7-9483-a19bc74d592f.png)

**Comment by wengcq** [comment] 2017-09-09 05:31
Confirmed that the tmux incompatibility issue can be resolved by combining cmder with babun. See the two screenshots attached. The bad one is using cmder with git for windows, the good one is using cmder with babun. 

![bad](https://user-images.githubusercontent.com/1478825/30237373-24335030-9563-11e7-9fe2-6654f05cd99b.png)
![good](https://user-images.githubusercontent.com/1478825/30237372-24321bc0-9563-11e7-8913-5118eeea57a9.png)

**Comment by takizo** [comment] 2017-09-09 09:27
It will surely work because it's using mintty.

**Comment by owkwen** [comment] 2017-10-31 15:42
Another way to avoid having the breaking drawing is to use WSL (Ubuntu bash on Windows) inside of cmder, [steps here](https://github.com/cmderdev/cmder/issues/901#issuecomment-237562623)

I always had this problem when I ssh to a server, use tmux and split screens vertically to have vim on the side. Vim drawing always broke, and I always had to redraw the screen using Ctrl+b Next Ctrl+b Previous. Now with bash on Windows it works fine.

You can easily test this by splitting vertically, run htop on the left (because it's moving and draws on all the space), open a long file in vim on the right, then page down the file until the end.

**Closed** 2017-11-25 00:23 UTC
Labels: upstream: ConEmu

**Comment by ColombianViking** [comment] 2018-11-16 09:50
Just throwing my 2 cents into this.
I've found that this issue does not arise if i enter a WSL instance beforehand.

To be clear:
Open cmder -> ssh -> tmux -> weird text shuffling might happen
Open cmder -> activate WSL instance (ubuntu 16.04 in my case) -> ssh -> tmux -> everything is nice

**Comment by nayrangnu** [comment] 2019-01-22 14:24
I can confirm that @Juan-Cortez3's answer appears to work. However, you may have Cygwin installed, but need to click the **Add/refresh default tasks...** button for it to be automatically added to the tasks list.

**Comment by georgix** [comment] 2019-07-17 22:17
Just an update: mintty included in cmder package works fine with ssh + tmux, but mintty need to be started separately to setup the font/theme.
