### ISSUE TITLE
Cmder keyboard shortcuts broken since v1.3.17

### ISSUE THREAD

**Issue by leo-liar** [cmderdev/cmder#2525] opened 2021-04-13 12:24 UTC
### Purpose of the issue
- [x] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [ ] Question

### Version Information

Tool | Version
--- | ---
Cmder mini | 1.3.18.1106
ConEmu | 21.03.04
PortableGit | 2.31.1

Windows 10 Enterprise 1909 (Build 18363.1443)

### Description of the issue

The recent switch to @chrisant996's [Clink](https://github.com/chrisant996/clink/) seems to have broken several keyboard shortcuts, e.g. `Ctrl + Alt + u` for traversing upwards in the directory structure.

---

<details><summary>Here is an excerpt of my output for <code>cmder_diag</code>:</summary>

```
------------------------------------
dir "C:\Users\[redacted]\Programme\Cmder"
------------------------------------
 Datenträger in Laufwerk C: ist Windows
 Volumeseriennummer: [redacted]

 Verzeichnis von C:\Users\[redacted]\Programme\Cmder

26.03.2021  16:28    <DIR>          .
26.03.2021  16:28    <DIR>          ..
08.04.2021  17:09    <DIR>          bin
26.03.2021  11:48           142.336 Cmder.exe
15.04.2020  08:28             2.484 ConEmuDefaultTerminal.lnk
08.04.2021  16:37    <DIR>          config
26.03.2021  16:24    <DIR>          icons
26.03.2021  11:47             1.069 LICENSE
26.03.2021  16:25    <DIR>          opt
26.03.2021  16:26    <DIR>          vendor
19.08.2019  00:36                 0 Version 1.3.12.915
24.11.2019  01:14                 0 Version 1.3.13.967
09.01.2020  04:47                 0 Version 1.3.14.982
26.06.2020  23:01                 0 Version 1.3.15.1010
30.07.2020  02:49                 0 Version 1.3.16.1035
26.03.2021  11:48                 0 Version 1.3.18.1106
               9 Datei(en),        145.889 Bytes
               7 Verzeichnis(se), 195.038.945.280 Bytes frei

------------------------------------
dir "C:\Users\[redacted]\Programme\Cmder\vendor"
------------------------------------
 Datenträger in Laufwerk C: ist Windows
 Volumeseriennummer: [redacted]

 Verzeichnis von C:\Users\[redacted]\Programme\Cmder\vendor

26.03.2021  16:26    <DIR>          .
26.03.2021  16:26    <DIR>          ..
26.03.2021  11:47    <DIR>          bin
26.03.2021  11:48    <DIR>          clink
26.03.2021  11:48    <DIR>          clink-completions
26.03.2021  11:47            13.213 clink.lua
26.03.2021  11:47               518 clink_settings.default
26.03.2021  11:47             3.903 cmder_exinit
08.04.2021  16:36    <DIR>          conemu-maximus5
26.03.2021  11:47            54.968 ConEmu.xml.default
26.03.2021  11:47            15.521 init.bat
26.03.2021  11:47    <DIR>          lib
26.03.2021  11:47             7.153 profile.ps1
26.03.2021  11:47    <DIR>          psmodules
26.03.2021  11:47                49 Readme.md
26.03.2021  11:47               732 sources.json
26.03.2021  11:47               397 user_aliases.cmd.default
26.03.2021  11:47               722 user_profile.cmd.default
26.03.2021  11:47               861 user_profile.ps1.default
26.03.2021  11:47               295 user_profile.sh.default
              12 Datei(en),         98.332 Bytes
               8 Verzeichnis(se), 195.038.945.280 Bytes frei

------------------------------------
dir /s "C:\Users\[redacted]\Programme\Cmder\bin"
------------------------------------
 Datenträger in Laufwerk C: ist Windows
 Volumeseriennummer: [redacted]

 Verzeichnis von C:\Users\[redacted]\Programme\Cmder\bin

08.04.2021  17:09    <DIR>          .
08.04.2021  17:09    <DIR>          ..
21.12.2020  14:30                42 cmdize.bat
25.02.2021  20:53               234 git.cmd
13.01.2021  14:17               628 nano.cmd
21.12.2020  13:41                39 perl.bat
08.04.2021  17:09                79 rc.bat
26.03.2021  11:47                84 Readme.md
21.12.2020  17:42               174 sqlite.cmd
               7 Datei(en),          1.280 Bytes

     Anzahl der angezeigten Dateien:
               7 Datei(en),          1.280 Bytes
               2 Verzeichnis(se), 195.038.945.280 Bytes frei

------------------------------------
dir /s "C:\Users\[redacted]\Programme\Cmder\config"
------------------------------------
 Datenträger in Laufwerk C: ist Windows
 Volumeseriennummer: [redacted]

 Verzeichnis von C:\Users\[redacted]\Programme\Cmder\config

08.04.2021  16:37    <DIR>          .
08.04.2021  16:37    <DIR>          ..
13.04.2021  13:35            15.113 clink.log
08.04.2021  10:30           390.852 clink_history
12.04.2021  14:29               285 clink_history_13932
09.04.2021  15:02                14 clink_history_13932.removals
13.04.2021  13:33             1.955 clink_history_21832
12.04.2021  10:19               112 clink_history_21832.removals
12.04.2021  10:13               132 clink_history_22600
09.04.2021  15:02                14 clink_history_22600.removals
26.03.2021  16:28               507 clink_settings
20.11.2018  14:12    <DIR>          profile.d
26.03.2021  11:47               887 Readme.md
08.04.2021  10:30            56.207 user-ConEmu.xml
26.03.2021  16:28               412 user_aliases.cmd
15.03.2021  09:21             1.081 user_profile.cmd
19.08.2019  00:36               861 user_profile.ps1
              14 Datei(en),        468.432 Bytes

 Verzeichnis von C:\Users\[redacted]\Programme\Cmder\config\profile.d

20.11.2018  14:12    <DIR>          .
20.11.2018  14:12    <DIR>          ..
               0 Datei(en),              0 Bytes

     Anzahl der angezeigten Dateien:
              14 Datei(en),        468.432 Bytes
               5 Verzeichnis(se), 195.038.924.800 Bytes frei

------------------------------------
where git
------------------------------------
C:\Users\[redacted]\Programme\Cmder\bin\git.cmd
C:\Users\[redacted]\Programme\PortableGit\mingw64\bin\git.exe
C:\Users\[redacted]\Programme\PortableGit\cmd\git.exe

------------------------------------
systeminfo
------------------------------------

Hostname:                                      [redacted]
Betriebssystemname:                            Microsoft Windows 10 Enterprise
Betriebssystemversion:                         10.0.18363 Nicht zutreffend Build 18363
Betriebssystemhersteller:                      Microsoft Corporation
Betriebssystemkonfiguration:                   Mitglied der Domäne/Arbeitsgruppe
Betriebssystem-Buildtyp:                       Multiprocessor Free
Registrierter Benutzer:                        [redacted]
Registrierte Organisation:                     [redacted]
Produkt-ID:                                    [redacted]
Ursprüngliches Installationsdatum:             [redacted]
Systemstartzeit:                               [redacted]
Systemhersteller:                              HP
Systemmodell:                                  [redacted]
Systemtyp:                                     x64-based PC
Prozessor(en):                                 1 Prozessor(en) installiert.
                                               [01]: Intel64 Family 6 Model 142 Stepping 10 GenuineIntel ~1792 MHz
BIOS-Version:                                  [redacted]
Windows-Verzeichnis:                           C:\WINDOWS
System-Verzeichnis:                            C:\WINDOWS\system32
Startgerät:                                    \Device\HarddiskVolume1
Systemgebietsschema:                           de;Deutsch (Deutschland)
Eingabegebietsschema:                          de;Deutsch (Deutschland)
Zeitzone:                                      (UTC+01:00) Amsterdam, Berlin, Bern, Rom, Stockholm, Wien
Gesamter physischer Speicher:                  15.747 MB
Verfügbarer physischer Speicher:               5.349 MB
Virtueller Arbeitsspeicher: Maximale Größe:    21.142 MB
Virtueller Arbeitsspeicher: Verfügbar:         3.598 MB
Virtueller Arbeitsspeicher: Zurzeit verwendet: 17.544 MB
Auslagerungsdateipfad(e):                      C:\pagefile.sys
Domäne:                                        [redacted]
Anmeldeserver:                                 [redacted]
Hotfix(es):                                    24 Hotfix(e) installiert.
                                               [01]: KB4601556
                                               [02]: KB4497165
                                               [03]: KB4516115
                                               [04]: KB4517245
                                               [05]: KB4528759
                                               [06]: KB4535680
                                               [07]: KB4537759
                                               [08]: KB4538674
                                               [09]: KB4541338
                                               [10]: KB4552152
                                               [11]: KB4560959
                                               [12]: KB4561600
                                               [13]: KB4565554
                                               [14]: KB4569073
                                               [15]: KB4576751
                                               [16]: KB4577586
                                               [17]: KB4577670
                                               [18]: KB4580325
                                               [19]: KB4586863
                                               [20]: KB4589211
                                               [21]: KB4598479
                                               [22]: KB4601395
                                               [23]: KB5000908
                                               [24]: KB5001648
Netzwerkkarte(n):                              3 Netzwerkadapter installiert.
                                               [01]: Intel(R) Ethernet Connection (4) I219-V
                                                     Verbindungsname: Ethernet
                                                     DHCP aktiviert:  Ja
                                                     DHCP-Server:     [redacted]
                                                     IP-Adresse(n)
                                                     [01]: [redacted]
                                               [02]: Intel(R) Dual Band Wireless-AC 8265
                                                     Verbindungsname: WLAN
                                                     Status:          Medien getrennt
                                               [03]: Generic Mobile Broadband Adapter
                                                     Verbindungsname: Mobilfunk
                                                     Status:          Medien getrennt
Anforderungen für Hyper-V:                     Erweiterungen für den VM-Überwachungsmodus: Ja
                                               Virtualisierung in Firmware aktiviert: Ja
                                               Adressübersetzung der zweiten Ebene: Ja
                                               Datenausführungsverhinderung verfügbar: Ja

------------------------------------
Make sure you sanitize this output of private data prior to posting it online for review by the CMDER Team!
------------------------------------
```

</details>

---

Please let me know if and how I can provide further information for resolving this issue.

**Comment by chrisant996** [comment] 2021-04-13 16:03
Clink 0.4.9 used Ctrl+Alt+U to go up.

Martin changed Clink 1.x to use Ctrl+PgUp to go up.

You can make a binding for Ctrl+Alt+U in the .inputrc file if desired. Refer to Clink docs for how to set key bindings.

**Comment by leo-liar** [comment] 2021-04-13 17:00
Ah, thanks. I will try to make a binding like that. Though I just tested `Ctrl + PgUp` and it didn't work either.\*
A small overview of shortcuts can be found on [Cmder's homepage](https://cmder.net/#shell) in the *Keyboard shortcuts* section but not all of them are Clink related (I think).

EDIT:
*) I tried `clink echo` and apparently `Ctrl + PgUp` is intercepted before it ever get's to **clink** because no key sequence is shown. Therefore it might work in general but for whatever reason not for me. (Might be language related or some other app using this sequence.)

EDIT 2:
Got it running by setting the `%CLINK_INPUTRC%` variable in my `user_profile.cmd` at Cmder startup and pointing it to `%CMDER_ROOT%\config` folder. I used your template and `clink echo` to create a simple *.inputrc* file there with my preferred key sequence `Ctrl + Alt + u`. Which solves my problem!

**Comment by chrisant996** [comment] 2021-04-14 16:21
Ah, ConEmu has a default key binding for Ctrl+PgUp = scroll buffer up one page.

- I'll add back Ctrl+Alt+U.
- I won't add back Alt+U (synonym for the same) because it conflicts with a Readline key binding, and I would like for Clink's default state to be as close to Readline's default behavior as feasible.
- It's possible to change any of ConEmu's key bindings via ConEmu's Settings UI.

You mentioned "several keyboard shortcuts" are broken.  What other ones did you observe?

**Comment by leo-liar** [comment] 2021-04-14 17:02
Thanks for adding `Ctrl + Alt + U` back!

I did check the ConEmu settings looking for a "traverse one directory up" shortcut when I first noticed it not working anymore but couldn't find anything. But I just took a look again and yes, `Ctrl + PgUp` is indeed used otherwise in ConEmu.

As for the "several keyboard shortcuts" ... I have to correct my inital statement, all other shortcuts seem to work fine. I'm sorry for the vague phrasing.

With you adding the old shortcut back I will close this issue as solved.

**Comment by chrisant996** [comment] 2021-04-14 17:32
Fixed by https://github.com/chrisant996/clink/commit/19c3f92ef1704780678560349cbf8e673916b88d.  Will appear in next release, within a week or two.

**Comment by daxgames** [comment] 2021-04-15 12:23
> EDIT 2:
> Got it running by setting the `%CLINK_INPUTRC%` variable in my `user_profile.cmd` at Cmder startup and pointing it to my `%CMDER_ROOT%\config` folder. I used your template and `clink echo` to create a simple _.inputrc_ file there containing only my preferred key sequence `Ctrl + Alt + U` for moving one folder up. Which very neatly solves my problem.

I might need to make this a part of Cmder since we try to be portable and all config SHOULD live in `%cmder_root%\config` folder.

**Closed by daxgames** 2021-04-15 12:23 UTC

**Comment by chrisant996** [comment] 2021-04-15 15:49
I don't understand why it was necessary to set CLINK_INPUTRC; can you explain further? It should have automatically loaded a .inputrc file from the profile directory.

**Comment by leo-liar** [comment] 2021-04-15 16:08
Because after using `clink info` I saw that the Cmder profile folder is *not* included within the standard search folders:
```
inputrc  : %clink_inputrc%
             (unset)
         : %userprofile%
             C:\Users\[redacted]\.inputrc
             C:\Users\[redacted]\_inputrc
         : %localappdata%
             C:\Users\[redacted]\AppData\Local\.inputrc
             C:\Users\[redacted]\AppData\Local\_inputrc
         : %appdata%
             C:\Users\[redacted]\AppData\Roaming\.inputrc
             C:\Users\[redacted]\AppData\Roaming\_inputrc
         : %home%
             C:\Users\[redacted]\Programme\WinPython\settings\.inputrc
             C:\Users\[redacted]\Programme\WinPython\settings\_inputrc
```
Without setting `%clink_inputrc%` my *.inputrc* file will not be loaded and the shortcut doesn't work.

**Comment by chrisant996** [comment] 2021-04-15 16:34
Got it, thanks.  It looks like a regression:

I tried and it seems that Cmder with Clink 0.4.9 loads a clink_inputrc file from %cmder_root%\config.

I'll try to track down how that happens with 0.4.9, and see if there's a straightforward way to fix the regression on Clink's end of things.  I would prefer to make a fix in Clink if possible, for greatest compatibility.  If necessary, a mitigation on Cmder's end of things could be reasonable as well.

**Comment by chrisant996** [comment] 2021-04-15 16:52
Found it:  in Clink 0.4.9 if `%CLINK_INPUTRC%` is not set, then Clink uses the profile directory as a default value (i.e. the directory where Clink stores its settings and history and etc -- the same directory that `--profile` overrides).

I'll make Clink 1.x behave similarly, though not identically:

First it will look in `%CLINK_INPUTRC%` (as it already does).
If not found there, it will look in the profile directory (new behavior).
If not found there, it will look in the rest of the locations (as it already does).

I'll update `clink info` accordingly as well.

**Comment by chrisant996** [comment] 2021-04-15 17:23
Fixed by https://github.com/chrisant996/clink/commit/a6d8d14627cb01f3a757a3a9231c7e9ddba3bce5.  Will appear in next release of Clink, probably in a week or two.
