### ISSUE TITLE
Cmder prompt screwed up with latest Windows 10 Build

### ISSUE THREAD

**Issue by ultralisk-** [cmderdev/cmder#820] opened 2016-01-31 05:06 UTC
Windows 10 Preview Build 14251
Cmder Version: 1.2.9

See this screenshot 
![cmder](https://cloud.githubusercontent.com/assets/5716849/12700390/1cf81508-c7d8-11e5-9abf-665a63f10d96.PNG)

I have multiple machines running Windows 10, both experienced this problem after installing the latest insider preview. I suspect Microsoft have broken something as I've noticed a few other bugs.

**Comment by amoshydra** [comment] 2016-01-31 14:15
I face this problem after upgrading to Build 14251 too. 
Is it fine to apply this workaround until the problem is fixed?

in `vendor/init.bat` change
`@prompt $E[1;32;40m$P$S{git}{hg}$S$_$E[1;30;40m{lamb}$S$E[0m`
to
`@prompt {lamb}`

**Comment by MartiUK** [comment] 2016-01-31 22:06
I can't reproduce this as I am not using the insider builds, could you report it to the clink repository?

**Comment by ultralisk-** [comment] 2016-01-31 22:28
Done: https://github.com/mridgers/clink/issues/377

**Comment by vensterlz** [comment] 2016-02-01 09:43
I have the same problem. It can be fixed by a reset. But cmder will have other weird problem.

**Closed** 2016-04-08 13:54 UTC
Labels: upstream: clink
