### ISSUE TITLE
λ symbol is missing in lastest full version

### ISSUE THREAD

**Issue by littlee** [cmderdev/cmder#2514] opened 2021-04-01 08:30 UTC
### Purpose of the issue
- [x] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [ ] Question

### Version Information

Cmder 1.3.18.1106
ConEmu 21.3.4.0

windows 10 19042.867

### Description of the issue
I download the full version from the release page and run Cmder.exe, but it seems some feature I liked before is missing

- the git message is not showing
- the character color is white, not green
- the `λ` symbol is also missing

![image](https://user-images.githubusercontent.com/7534668/113265707-0867b300-9307-11eb-93e2-15ff3bb2626f.png)

**Comment by littlee** [comment] 2021-04-01 08:56
@chrisant996 I can not run `clink info`, the `clink` command is not found
![image](https://user-images.githubusercontent.com/7534668/113269476-0ef82980-930b-11eb-945c-d97530f27f11.png)


I follow these steps to run cmder, without the optional step 3
https://github.com/cmderdev/cmder#single-user-portable-config

**Comment by chrisant996** [comment] 2021-04-01 09:01
Ok. It is indeed not using Clink.

It sounds like one or more steps may have been performed differently than was intended.

How is the default Task configured for new console tabs?  If it isn't configured to run the %cmder_root%\vendor\init.bat script then it isn't configured to use Clink, and that would be why it behaves differently than remembered.

**Comment by littlee** [comment] 2021-04-02 01:19
@chrisant996 here is the screenshot of my default task setting，I did not change any setting after downloading the full version from release page
![image](https://user-images.githubusercontent.com/7534668/113369628-5676c800-9394-11eb-9b42-66a807cee59e.png)
![image](https://user-images.githubusercontent.com/7534668/113369651-61315d00-9394-11eb-9678-fa62fb29b5d1.png)

**Comment by chrisant996** [comment] 2021-04-02 04:05
I don't know what to tell you. The screen shot that was shared shows Clink is not being started, and doesn't show any errors being reported.

What troubleshooting investigations have you done so far?

What is different about this specific installation, compared to other installations where it's working as expected?

**Comment by littlee** [comment] 2021-04-02 06:38
@chrisant996 is there any troubleshooting documentation?

I will try to install some previous version for now

**Comment by chrisant996** [comment] 2021-04-02 08:40
- Try running `clink info`.  Since that wasn't found, try running it directly via `d:\gg\vendor\clink\clink info`.
- Upload the contents of the log file listed in the output from `clink info`.
- Check whether antivirus may have blocked Clink from running, or blocked some part of Cmder from running.
- Check whether Clink can be started on its own (start `cmd.exe` by itself outside of Cmder, and then run `d:\gg\vendor\clink\clink inject` -- what happens?)
- Is the OS 32 bit, or 64 bit?

> @chrisant996 is there any troubleshooting documentation?

I don't know if there is troubleshooting documentation for Cmder or ConEmu.  There isn't troubleshooting documentation for Clink, apart from running `clink info` and collecting the log file.  So far I haven't really seen any problem occur more than once or twice, so it's unclear how to write a do-it-yourself troubleshooting document.

**Comment by daxgames** [comment] 2021-04-11 20:56
I just downloaded and do not see this issue.

**Comment by daxgames** [comment] 2021-04-15 12:13
Copy and paste output of `%cmder_root%\vendor\bin\cmder_diag.cmd`

**Comment by chrisant996** [comment] 2021-04-15 15:52
I suspect anti virus may have blocked clink from running.

**Comment by daxgames** [comment] 2021-04-15 19:21
@chrisant996 Very possible.

**Comment by littlee** [comment] 2021-04-16 06:23
@daxgames running `cmder_diag.cmd` in version 1.3.18 seems trigger a dead loop

```
PS D:\cmder1318> .\vendor\bin\cmder_diag.cmd
------------------------------------
dir ""
------------------------------------
 驱动器 D 中的卷没有标签。
 卷的序列号是 F0AF-D103

 D:\cmder1318 的目录

2021/04/16  14:15    <DIR>          .
2021/04/16  14:15    <DIR>          ..
2021/03/26  17:47    <DIR>          bin
2021/03/26  17:48           142,336 Cmder.exe
2021/04/16  14:15    <DIR>          config
2021/03/26  17:47    <DIR>          icons
2021/03/26  17:47             1,069 LICENSE
2021/03/26  17:47    <DIR>          opt
2021/03/26  17:48    <DIR>          vendor
2021/03/26  17:48                 0 Version 1.3.18.1106
               3 个文件        143,405 字节
               7 个目录 252,915,576,832 可用字节

------------------------------------
dir "\vendor"
------------------------------------
 驱动器 D 中的卷没有标签。
 卷的序列号是 F0AF-D103

 D:\ 的目录

找不到文件

------------------------------------
dir /s "\bin"
------------------------------------
 驱动器 D 中的卷没有标签。
 卷的序列号是 F0AF-D103

 D:\cmder1318 的目录

2021/03/26  17:47    <DIR>          bin
               0 个文件              0 字节

 D:\cmder1318\vendor 的目录

2021/03/26  17:47    <DIR>          bin
               0 个文件              0 字节

 D:\cmder1318\vendor\git-for-windows 的目录

2020/10/24  06:08    <DIR>          bin
               0 个文件              0 字节

 D:\cmder1318\vendor\git-for-windows\mingw64 的目录

2021/03/26  17:48    <DIR>          bin
               0 个文件              0 字节

 D:\cmder1318\vendor\git-for-windows\usr 的目录

2021/03/26  17:48    <DIR>          bin
               0 个文件              0 字节

 D:\cmder_mini 的目录

2020/07/30  08:49    <DIR>          bin
               0 个文件              0 字节

 D:\cmder_mini\vendor 的目录

2020/07/30  08:49    <DIR>          bin
               0 个文件              0 字节
... a lot of similar output ...
```

**Comment by daxgames** [comment] 2021-04-16 12:59
I don't know you have got issues on your system preventing things from working

**Comment by chrisant996** [comment] 2021-04-16 16:41
Clearly the `%cmder_root%` environment variable is not set.
That's why the diag script reports `dir ""` near the beginning.

When I use `set cmder_root=` to clear it on my computer and then run `cmder_diag.cmd`, then I get the same messed up output as above.

Fix the environment variable.

**Comment by daxgames** [comment] 2021-04-16 17:19
If cmder_root is not set init.bat sets it.  If it is set outside init.bat it uses it.  I noted earlier that the user had what looked like old cmder folders based on thenprov8ded path statement.  The env is messed up and until it can be cleaned up not much we can do to help.

I suggest:

1. REMOVE ALL REFERENCES TO ANY CMDER FOLDER FROM THE ENV.
2. Download fresh `cmder.zip`
3. Extract it.
4. Run `cmder.exe`
5. If there is still issues run `set cmder_root="%cd%"`
6. Run `cmder_diag.cmd`

**Comment by chrisant996** [comment] 2021-04-23 21:55
[Clink v1.2.4](https://www.github.com/chrisant996/clink/releases) now includes error reporting and logging when inject fails.  That should make it possible to diagnose why Clink isn't able to be injected.

**Comment by daxgames** [comment] 2021-05-04 22:08
@littlee ???

**Comment by cooperaustinj** [comment] 2021-09-02 23:18
I had the same issue.  Fixed it by deleting clink from my Program Files and re-running the installer.

Still have no idea why it just up and broke one day.

**Comment by daxgames** [comment] 2021-10-15 16:55
@mianxiangdahai This is not an issue the Cmder team can fix.

**Comment by jfgg95** [comment] 2021-11-22 03:50
![image](https://user-images.githubusercontent.com/28002478/142797426-4fd1e197-5990-4ca0-85cf-bcf2b777d29f.png)
Today I downloaded the latest version（v1.3.18） of cmder，and encountered the same problem。
then i try [this](https://github.com/cmderdev/cmder/issues/2603#issuecomment-921786098),it doesn't work.

The Cmder message is:
"Unable to inject CLink
See log file for details ({PATH TO LOG})"

clink log
0218 inject                    518 ---- 2021/11/22 11:33:14.489 -------------------------------------------------
0218 inject                    519 Injecting Clink...
0218 inject_dll                257 Version: 1.2.32.510fbd
0218 inject_dll                258 Arch: x64
0218 inject_dll                259 DLL: C: \Local\Temp\clink\dll_cache\1.2.32.510fbd_0546ea31\clink_dll_x64.dll
0218 inject_dll                261 Parent pid: 24768
0218 inject_dll                266 EXE version: 00010002 00000020

then i download the latest clink(1.2.46).it works!
![image](https://user-images.githubusercontent.com/28002478/142798174-73608360-eaeb-4d83-b268-ff4fadb19232.png)

**Comment by cooperaustinj** [comment] 2021-11-22 03:51
I fixed this by getting a 2021 MacBook Pro and not using Cmder.

**Comment by chrisant996** [comment] 2021-11-22 05:58
> 0218 inject_dll                259 DLL: C: \Local\Temp\clink\dll_cache\1.2.32.510fbd_0546ea31\clink_dll_x64.dll

I think the path there is not what is actually listed in the log, right?
It has been edited to hide a user name, right?
And the user name contains non-ASCII characters, right?

There was an issue in Clink v1.0.0 and higher that made it only work with non-ASCII user names if the system code page was set to UTF8.

That issue was fixed in Clink v1.2.43, so now the system code page doesn't need to be UTF8.

> then i download the latest clink(1.2.46).it works!

That's great to hear!

**Comment by jfgg95** [comment] 2021-11-22 06:11
> I think the path there is not what is actually listed in the log, right? It has been edited to hide a user name, right? And the user name contains non-ASCII characters, right?
yes, the real path has been edited to hide the username which is formed by chinese character.

**Comment by daxgames** [comment] 2021-11-22 13:10
There will be a release of Cmder soon that includes the newer Clink with this fix.

**Comment by chrisant996** [comment] 2021-11-22 16:32
> There will be a release of Cmder soon that includes the newer Clink with this fix.

Sweet!

**Closed** 2022-04-27 22:41 UTC
Labels: 👀 Awaiting Response
