### ISSUE TITLE
How to create an alias for 2 commands in ConEmu?

### ISSUE THREAD

**Issue by mlotfi2005** [cmderdev/cmder#1334] opened 2017-04-06 18:59 UTC
I have two alias in user-aliases.cmd:

title=cmd /c RenameTab "$*" 
ap5pro=ssh  170.63.170.72
When calling the first:

$ title "sometitle"
It works; the tab title changes to "sometitle"

AND when I call the second:

$ ap5pro
I got the ssh asking me for password, so everything is working.

How can I combine the above two comnands into one in user-aliases.cmd?

I did these :

ap5pro=RenameTab ap5pro $t ssh 170.63.170.72

and

ap5pro=RenameTab ap5pro & ssh 170.63.170.72

but only ssh execute, never RenameTab

**Comment by jrappen** [comment] 2017-04-06 20:12
@mlotfi2005 Perhaps your issue is a duplicate of #1325?

**Closed** 2019-06-01 10:46 UTC
Labels: 👀 Awaiting Response
