### ISSUE TITLE
Previous commands are cleared after closing a file

### ISSUE THREAD

**Issue by dseals3** [cmderdev/cmder#2297] opened 2020-04-10 23:39 UTC
### Purpose of the issue
- [ ] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [x ] Question

### Version Information

Newest Version

Windows 10 Home 1903
### Description of the issue

Hello, so I just installed cmder, and my issue is more really of a question. I have used terminals before, but never on Windows, so I installed cmder yesterday and I have been fiddling with it to customize it to my liking, so that is where this comes from.

I cannot figure out how to make my previous commands stay in the terminal window after closing a file. Is this a setting? 

For example. to get to my directory for school, I have to run an ssh command, put in my password, cd into the appropriate directory, and vim into my file. That is a total of 5 or so commands. On any regular terminal that I have used, after I close that file in vim, those 5 commands will still be on the screen. Cmder doesn't seem to work that way. Every time I close the file I am currently looking at with vim, the terminal window is completely empty, other than a single prompt.

How do I fix this or change this setting? To me, this should be default. If I can't figure this out then I will be uninstalling cmder because this is a deal breaker.

Thanks so much

**Comment by daxgames** [comment] 2020-04-12 15:14
Duplicate of #2289.

@dseals3 I just did the following:

1. Start `Cmder`.
2. Run several shell commands.
3. Run `vim` and edited a file.
4. Exited `vim`.
5. All screen history remained on the screen.
6. Run `ssh [host]` and login
7. Run several shell commands.
8. Run `vim` and edited a file.
9. Exited `vim`.
10. All screen history from local and ssh session remained on the screen.
11. Exited `ssh`.
12. All screen history from local and ssh session remained on the screen.

**Closed by daxgames** 2020-04-12 15:14 UTC
Labels: 😰 Can't Reproduce

**Comment by daxgames** [comment] 2020-04-12 15:31
Did either of you try this: https://vi.stackexchange.com/questions/432/prevent-vim-from-clearing-the-terminal-after-exit

**Comment by daxgames** [comment] 2020-04-12 15:31
You could add set t_te= to your ~/.vimrc and it will be set each time you run vim.

**Comment by PrestonTaylor** [comment] 2021-04-02 00:40
If anyone finds this in the future just start your terminal in bash/unix type terminal rather than starting from cmd and moving into bash. The issue is the way windows cmd prompt handles exit codes.
