### ISSUE TITLE
Arrow keys corrupt input line

### ISSUE THREAD

**Issue by darsain** [cmderdev/cmder#977] opened 2016-06-04 11:38 UTC
So this happens when I press UP a few times, than write "clear" and press Enter:

![cmder](https://cloud.githubusercontent.com/assets/538801/15799317/07d7c176-2a59-11e6-9e50-5fc86710f4aa.gif)

The same thing happens for all arrow keys, just the char is a bit different.

I'm on 1.3pre mini, Win8.1. Any ideas? :)

**Comment by Stanzilla** [comment] 2016-06-04 17:10
We are waiting for a new clink release where this is fixed https://github.com/mridgers/clink/commit/c1ae9938de8605d9aed64d1cb1df893acfd3eff7

Dupe of https://github.com/cmderdev/cmder/issues/968

**Comment by darsain** [comment] 2016-06-04 17:26
Oh, saw that issue, but thought this was something else, as it doesn't perma-recall parts of history states, just corrupts the lambda. Anyway, thx for the info :)

**Comment by Stanzilla** [comment] 2016-06-05 00:42
Well if could still be something else, guess we'll have to wait and see. Or, if you want and can, compile a version of clink for yourself and test.

**Closed** 2016-07-14 08:30 UTC
Labels: Confirmed, Duplicate, upstream: clink

**Comment by Pathduck** [comment] 2016-07-15 15:07
Does not appear to be fixed in 1.3.0 or maybe I'm doing something wrong here?

![cmder-arrow-bug](https://cloud.githubusercontent.com/assets/1493836/16878906/934dd252-4aae-11e6-8422-d8d780776e56.png)

These do not appear in 1.2.9.

**Comment by Stanzilla** [comment] 2016-07-15 15:18
Please try with a clean installation, I cannot reproduce that here.

**Comment by Pathduck** [comment] 2016-07-15 16:32
This is a clean install of cmder_mini.zip 1.3.0. 
Windows 10 Pro x64.

Are there any 

Getting the following on startup, seems OK apart from the git version warning, but I also tried unsetting my PATH to default. Also tried a reboot if anything was stuck in memory. 

`Generating clink initial settings in "D:\bin\Cmder\config\settings"
Additional *.lua files in "D:\bin\Cmder\config" are loaded on startup.
Found old git version in "d:\bin\cygwin", but not using...
Creating intial user-aliases store in "D:\bin\Cmder\config\user-aliases.cmd"...
        1 file(s) copied.
Creating user startup file: "D:\bin\Cmder\config\user-profile.cmd"`

**Comment by Pathduck** [comment] 2016-07-15 17:04
Ok here's something interesting; figured some of the dot-files in my HOME might be doing something, and narrowed it down to .inputrc.

It looks like this:

```
set meta-flag on
set convert-meta off
set output-meta on
set completion-ignore-case on 
```

I also figured it's the "set convert-meta off" that does it. I really have no idea why I even have this file, I think it was something old dragged along since forever.

Question remains though, why would Cmder/ConEmu/Clink even read this file?

**Comment by darsain** [comment] 2016-07-18 09:55
Jesus, yeah! I also had `.inputrc` with `meta` settings in it, and after commenting them out the issue disappeared. Thx a lot! :) The specific settings in my case were:

```
# Allow UTF-8 input and output, instead of showing stuff like $'\0123\0456'
set input-meta on
set output-meta on
set convert-meta off
```

I'm sure I copied that whole `.inputrc` file from someone elses dotfiles repo, but it wasn't causing issues until now. Is this something Clink people should fix?
