### ISSUE TITLE
After entering the alphabet, sometimes press the upper and lower keys first letter will not disappear

### ISSUE THREAD

**Issue by shiroming** [cmderdev/cmder#685] opened 2015-10-28 01:57 UTC
This question has always been, is I set up the problem?

**Comment by shiroming** [comment] 2015-10-28 02:08
I solved it.
Modified cmder>>config>>cmder.lua
First line function
```
function lambda_prompt_filter()
    clink.prompt.value = string.gsub(clink.prompt.value, "{lamb}", "λ")
end
```
TO
```
function lambda_prompt_filter()
    clink.prompt.value = string.gsub(clink.prompt.value, "{lamb}", "~")
end
```

**Comment by MartiUK** [comment] 2015-10-28 08:29
Duplicate of #553

**Closed by MartiUK** 2015-10-28 08:29 UTC
Labels: Duplicate
