### ISSUE TITLE
Terminate batch job bug (I think?)

### ISSUE THREAD

**Issue by m3hr** [cmderdev/cmder#108] opened 2014-01-04 01:30 UTC
When I boot a WEBrick server and CTRL-C to close it, the running server stuff goes away. Then:
`Terminate batch job (Y/N)?`
Y
`Terminate batch job (Y/N)?`
Y
`'Y' is not recognized as an internal or external command, etc`

And then I can input other commands. I'd love for this to get fixed, it slows down my Nanoc workflow by a lot. Thanks!

**Comment by Jackbennett** [comment] 2015-10-16 11:15
clink and cmder have moved on a lot I can't seem to reproduce this.

I tried serving a node static server and closing it with ctrl-c once stops it as expected.

**Closed by Jackbennett** 2015-10-16 11:15 UTC
Labels: upstream: clink

**Comment by edmundo096** [comment] 2018-02-27 16:49
Probably what samvasko pointed to, there is a setting inside `\cmder\config\settings` file:

```
# name: Auto-answer terminate prompt
# type: enum
#  0 = Disabled
#  1 = Answer 'Y'
#  2 = Answer 'N'
# Automatically answers cmd.exe's 'Terminate batch job (Y/N)?' prompts. 0 =
# disabled, 1 = answer 'Y', 2 = answer 'N'.
terminate_autoanswer = 1
```

**Comment by DRSDavidSoft** [comment] 2019-03-09 11:35
Duplicate of #1666.
