### ISSUE TITLE
Version 1.3.15.1010: "The system cannot find the file specified" on startup 

### ISSUE THREAD

**Issue by Pathduck** [cmderdev/cmder#2345] opened 2020-07-09 21:06 UTC
### Purpose of the issue
- [x] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [ ] Question

### Version Information
Version 1.3.15.1010

OS Name	Microsoft Windows 10 Pro
Version	10.0.18363 Build 18363
System Type	x64-based PC

### Description of the issue

After installing Version 1.3.15.1010 from cmder_mini.zip in a clean directory, Cmder launches with the following:
```
Generating clink initial settings in "D:\bin\Cmder-new\config\settings"
        1 file(s) copied.
Additional *.lua files in "D:\bin\Cmder-new\config" are loaded on startup.
The system cannot find the file specified.
Creating initial user_aliases store in "D:\bin\Cmder-new\config\user_aliases.cmd"...
        1 file(s) copied.
Creating user startup file: "D:\bin\Cmder-new\config\user_profile.cmd"
        1 file(s) copied.
```

Subsequent launches will output just the "The system cannot find the file specified." error message.

I put on debug logging, the relevant output seemed to be:
```
DEBUG(init.bat): Preferring Windows commands

The system cannot find the file specified.
DEBUG(:enhance_path): Env Var INSIDE PATH \=\\ - found=0
``` 
I don't really know what to look for between init.bat and enhance_path?

Full debug log: https://pastebin.com/csTDeSty
Output of cmder_diag.cmd: https://pastebin.com/7rQWCKDq

Issue seems similar to: https://github.com/cmderdev/cmder/issues/2340
I tried the [fix linked in that issue](https://ci.appveyor.com/project/MartiUK/cmder/builds/33796435/artifacts) but it didn't change anything for me.

As said, this is a completely clean install of Cmder. So I suspect something on my system is interfering, but I never had this in Version 1.3.14.982.

**Comment by Pathduck** [comment] 2020-07-09 22:14
I've managed to narrow it down to possibly this line in `lib_path.cmd`:
`    dir "%add_path%" | findstr -i "\.COM \.EXE \.BAT \.CMD \.PS1 \.VBS" >NUL`

Adding some debug output I get:
```
GIT_INSTALL_ROOT=d:\bin\cygwin\bin
ADD_PATH=d:\bin\cygwin\bin\usr\bin
The system cannot find the file specified.
```

That ADD_PATH is definitely wrong. And then it tries to `dir` it. But no idea yet where it's set like that. 

My Cygwin Git is located at `d:\bin\cygwin\bin\git.exe`. There is no `usr\bin` under there.

**Comment by daxgames** [comment] 2020-07-09 22:25
Try this `dir "%add_path%" >NUL | findstr -i "\.COM \.EXE \.BAT \.CMD \.PS1 \.VBS" >NUL` and let me know if it solves the issue.

**Comment by Pathduck** [comment] 2020-07-10 07:29
@daxgames Thanks! I've tried it and it does hide the error message.

I was thinking something similar when I found it, but I think better to use a `2>NUL` otherwise the output from dir will also be hidden and defeat the purpose of the line.

Where does the `usr\bin` come from? I assume it's been in for a long time just never threw an error like that?

**Comment by daxgames** [comment] 2020-07-10 10:48
We assume git is from a Git for Windows installation and not Cygwin.  This is a structure we expect from Gitfor Windows so we look for it and add it if it's there.

1.3.15 makes the `enhance_path_rexursive` function smarter by adding this line to only add to the path if one of these files types is found in the folder.

This will be included in the next release.

**Closed by daxgames** 2020-07-10 10:48 UTC

**Comment by Gildedter** [comment] 2022-09-07 06:18
I'm having the same issue on version `1.3.19.1181`, I have Git for Windows installed via scoop, and copying the whole zip contents on my Laragon bin directory since its running an outdated version of Cmder (1.3.2 specifically)

**Comment by daxgames** [comment] 2022-09-08 11:29
@Gildedter does cmder behave the same way when using using it stand alone outside laragon.

I do not use scoop and therefore have not tested your scenario but I can if you can reproduce the error outside laragon.

**Comment by daxgames** [comment] 2022-09-08 12:40
@Gildedter I just installed scoop and git and do not have the issue you describe beyond first launch after installing git using scoop.

![image](https://user-images.githubusercontent.com/7318053/189124024-b36f0294-7c58-4982-bea8-079fddbdcfe9.png)
