### ISSUE TITLE
Lingering first letter when invoking previous commands

### ISSUE THREAD

**Issue by suimong** [cmderdev/cmder#668] opened 2015-10-16 17:32 UTC
I have experienced this rather little but annoying problem: In a clean cmd session, whenever I typed in a command more than (including) 5 characters and hit enter, regardless of the validity of that command, when I then hit the up arrow to navigate to the previous command and then hit down arrow, the first character of that command will always linger at the beginning of that line until I hit enter.
This problem occurs on both normal and elevated cmd sesion, and does not exhibit itself on a powershell session. It does not occur when running conemu explicitly.
My machine runs Windows 8.1 pro, and the same problem happens on my freshly installed Windows 10 pro VM.
Please let me know if you need any other diagnostic information. Thanks!

**Comment by Stanzilla** [comment] 2015-10-22 01:05
Dupe of https://github.com/cmderdev/cmder/issues/553

**Closed by Stanzilla** 2015-10-22 01:05 UTC
