### ISSUE TITLE
Default bash tasks in ConEmu don't work in mini installations

### ISSUE THREAD

**Issue by jordancoll** [cmderdev/cmder#1497] opened 2017-09-23 17:38 UTC
The default `bash::*` tasks try to launch `%ConEmuDir%\..\git-for-windows\bin\bash`

https://github.com/cmderdev/cmder/blob/a5eb4d7b4fd8cd2dec1ba9fe7e879733d7146a4b/config/ConEmu.xml#L558

I suggest changing the default tasks to use `GIT_INSTALL_ROOT` as it should point to the user's preferred git installation.

**Comment by Stanzilla** [comment] 2018-03-24 01:44
%GIT_INSTALL_ROOT% is not set at that time though :/

**Comment by i-s-o** [comment] 2018-03-24 14:56
@Stanzilla is `%GIT_INSTALL_ROOT%` a cmder-specific env var? I always get confused by this one because it sounds like it is set by git-for-windows. I expected it to be called something like `%cmder_git_root%` if it was set by cmder.

**Comment by Stanzilla** [comment] 2018-03-24 14:59
Yeah, we set it in init.bat

**Comment by DRSDavidSoft** [comment] 2018-04-07 02:56
@Stanzilla @daxgames How about not specifying anything, and launch `bash` from user's %PATH%?

I mean should the user have installed any other bash (WSL, msys2, Cygwin) without a Git, it should run that too.

**Comment by daxgames** [comment] 2018-04-07 03:59
The default bash task is designed to work with vendored git.  So the path is correct and required.  We can't launch a get that we have not discovered yet and so far the only Discovery we have is in the Annette. Bat for command sessions so I don't know what to say.

**Comment by daxgames** [comment] 2018-04-07 04:00
why don't the users that want to use mini just edit the task to point to their own Bash

**Comment by DRSDavidSoft** [comment] 2018-04-07 05:52
@daxgames We should devise a plan on Cmder first launch:

1) Cmder full: use the vendored git unchanged
2) Cmder mini:
    a) Git exists on any directory in path: modify ConEmu.xml to use that
    b) No Git or Bash exist at all: remove the option from ConEmu.xml

How about it?

**Comment by Stanzilla** [comment] 2018-04-07 09:08
That would mean we have to change the file during the build process and make that way more complex, no?

**Comment by Stanzilla** [comment] 2018-04-07 11:25
Yeah agree

**Comment by DRSDavidSoft** [comment] 2018-04-07 16:09
@daxgames It can easily be made from a sample file, if the user file does not exist then make a user config from the sample. However, I do strongly recommend checking before each startup, or at least giving the user an option to rebuild it manually. Think of a scenario when user installs Cmder mini then proceeds to install WSL or msys2.

<sub>(P.S. my username is DR **S** David Soft)</sub>

**Comment by daxgames** [comment] 2018-04-07 18:02
@DRSDavidSoft  That means maintaining two different 'default' conemu.xml files.  One for cmder and one for cmder mini.  It's already a pain to maintain one copy of a change is needed.

I think we just need to add a section to the readme.md explaining the task is there for the full cmder but can be altered or added to in the case a user has a prior installed bash shell.  I think were trying to fix something that does not need fixing but might need documenting.  Another option is another command line art for the launcher where a user can specify a git install root but I'm not real hip on the idea because as you have said there are many different bash shells that can be installed and not all Will launch exactly the same way.

Maybe we even rename the vendored menu option to `cmder bash` to denote the built in nature of the censored git-for-windows.

**Comment by DRSDavidSoft** [comment] 2018-04-08 05:40
@daxgames While documenting this issue in README is an _acceptable_ alternative to fixing a problem that we're sure not a lot of people might occur, I think it's still a better solution to try and fix it IF a) the fix is easy and b) it doesn't break other parts of Cmder.

Regarding in naming it `cmder bash` I'd say it would be an appropriate name because the way cmder currently handles it is by _only_ calling vendored Git's bash.

This is acceptable behavior to many users of Cmder, and this issue can be closed. However, I'd like to ask to write a fix for it, by changing a small portion of Cmder logic: creating the `ConEmu.xml` based on user machine's configuration. That way a better (an easier) integration between Cmder and external shells installed on user's machine is guaranteed.

**Comment by daxgames** [comment] 2018-04-08 12:02
@DRSDavidSoft. PRs are always welcome and no permission required. Just understand the only time the default conemu.xml is used or references is on initial install.  Just don't break the current handling of the conemu.xml after that initial install.

**Comment by Stanzilla** [comment] 2018-04-08 12:58
Why not build the problem into the error message? If it says "CMDER Shell Initialization has Failed, are you trying to use bash in cmder_mini?" Or something like that, it should be pretty clear?

**Comment by DRSDavidSoft** [comment] 2018-04-08 16:47
@Stanzilla that'd also make sense,

- if Git is not found don't initialize it
- if bash is selected but not found, show sensible error
- on first launch if mini version, remove bash from tasks

That way we'd avoid this issue on fresh installs, and won't introduce breaking changes to previous installs by displaying an appropriate message.

**Comment by Stanzilla** [comment] 2018-04-11 11:37
How exactly did 1.3.5 do this? Because it's actually a regression

**Comment by jods4** [comment] 2018-04-11 12:05
This is a regression indeed.
I had 1.3.5 and it worked fine. I upgraded to 1.3.6-pre1, did not change my config at all and now I have this error.

It's not exclusively related to bash. I have the same error in all my tasks: `cmd`, `powershell`, `bash`, doesn't matter.

**Comment by daxgames** [comment] 2018-04-12 13:27
@jods4. What error?

**Comment by jods4** [comment] 2018-04-12 13:30
@daxgames 
```
ERROR: C:\ProgramData\Cmder\vendor\git-for-windows\cmd\git.exe
CMDER Shell Initialization has Failed
```

Also, see #1726. This is where I come from and it was closed as a duplicate of this one.

**Comment by daxgames** [comment] 2018-04-12 23:24
@jods4. You say you get this error in all shells not just a cmder shell?

**Comment by jods4** [comment] 2018-04-13 05:36
@daxgames I mean in all kind of tasks inside Cmder.

**Comment by vBm** [comment] 2018-04-16 15:31
@daxgames 
#1745 does fix this issue for me, thank you for that.

**Comment by Stanzilla** [comment] 2018-04-19 07:09
The latest ConEmu build (https://conemu.github.io/blog/2018/04/16/Build-180416.html) has an interesting bug fix:

```
conemu#1513: Fix erroneously trimmed leading " in commands  cmd /c "-new_console script.bat argument".
```

maybe that was the reason why I could not make it work before.

**Closed** 2019-06-01 06:46 UTC
Labels: 🎨 Type: Enhancement, 👀 Awaiting Response
