### ISSUE TITLE
Why my cmder suddenly has a different background color

### ISSUE THREAD

**Issue by abrhambas01** [cmderdev/cmder#2045] opened 2019-02-24 04:49 UTC
When I put yarn run watch that command in terminal. It suddenly has a different background color

![image](https://user-images.githubusercontent.com/12043306/53295273-a9cfd100-3832-11e9-8454-4719af649849.png)

it just automatically adds a background color when my background color is white?

**Comment by DRSDavidSoft** [comment] 2019-03-07 07:05
1. do `yarn --version`, make sure you have the latest yarn installed
2. right click on `Cmder.exe`, check the product version and make sure you have the latest stable version
3. try setting up Cmder with either [Hyper](https://github.com/cmderdev/cmder/wiki/Seamless-Hyper-integration) or [FluentTerminal](https://github.com/cmderdev/cmder/wiki/Seamless-FluentTerminal-Integration) to see if you get the same type of background color
4. try the same `yarn run watch` command from `cmd.exe` instead of Cmder to see if the issue continues
5. temporarily download a fresh copy of **Portable** ConEmu from [here](https://www.fosshub.com/ConEmu.html) (_not_ the PortableApps.com edition) and test with it
6. try to resize both Cmder and/or ConEmu window when the white background color appears
7. open a new issue here **in case the problem is reproducible**: https://github.com/yarnpkg/yarn/issues
8. test the same version of yarn + Cmder on a different machine if possible.

**Comment by daxgames** [comment] 2019-05-11 12:13
Closing due to non response.

**Closed by daxgames** 2019-05-11 12:13 UTC
