### ISSUE TITLE
Problems with node

### ISSUE THREAD

**Issue by okaufmann** [cmderdev/cmder#790] opened 2016-01-06 23:39 UTC
If I start cmder in a project dir where I have installed node packages I got this error on startup
```
C:\tools\cmder/vendor/clink-completions/npm_prompt.lua:11: attempt to concatenate local 'package_version' (a nil value)
```

Cmder won't run correct and showed up like this:
![image](https://cloud.githubusercontent.com/assets/4414498/12158076/02538106-b4d7-
![image](https://cloud.githubusercontent.com/assets/4414498/12158078/07e1e4e6-b4d7-11e5-9368-fe6d45d4d287.png)

Anyone else can verify this behaviour?

**Comment by vladimir-kotikov** [comment] 2016-01-07 10:04
Dupe of #700

**Closed** 2016-01-07 10:42 UTC
Labels: Outdated Installation
