### ISSUE TITLE
The shell console is flushed when exiting from the vi editor. 

### ISSUE THREAD

**Issue by FavonianKong** [cmderdev/cmder#2405] opened 2020-10-10 11:03 UTC
### Purpose of the issue
- [ ] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- Question

### Version Information

version status: 191012 

Microsoft Windows 10.0.19041.388
### Description of the issue

When I work in vi and exit vi, all the original output on the shell console is flushed and only the blank page is left. Is there any setting that won't let it refresh, or am I setting something wrong?

This wont happen when I use the window terminal (version: 1.0.1811.0). Any ideas?

**Comment by rakib-hasan** [comment] 2020-10-19 09:37
@FavonianKong , 
If this happens when you are in ssh session to some Ubuntu system, check #2349 .

**Comment by FavonianKong** [comment] 2020-11-17 03:40
@rakib-hasan ,
Hi, this problem is disapper when I change the the version to 180206.  That's weird :(

**Comment by daxgames** [comment] 2020-12-23 11:50
Duplicate of #2349

**Closed by daxgames** 2020-12-23 11:50 UTC
