### ISSUE TITLE
Downloads for v1.2 missing DLLs

### ISSUE THREAD

**Issue by WenceslaoGrillo** [cmderdev/cmder#558] opened 2015-07-17 15:13 UTC
Running cmder.exe gives the following error message:

---------------------------
Cmder.exe - System Error
---------------------------
The program can't start because api-ms-win-crt-runtime-l1-1-0.dll is missing from your computer. Try reinstalling the program to fix this problem. 
---------------------------
OK   
---------------------------

It seems to be caused by having compiled with Visual Studio 2015 and not included the redistributables in the archive. (Allegedly, the redistributables can be downloaded from MS, but in my pc they fail to install, so I can't confirm).

**Comment by CameronAM** [comment] 2015-07-20 06:43
I am also getting this error.

**Comment by mikesteele81** [comment] 2015-07-20 20:29
I saw somewhere that the Visual Studio Redistributable 2015 is required. Microsoft normally makes these available as separate downloads, but I was unable to find it on their site. I installed Visual Studio 2015 Community Edition, which comes with the 2015 redistributable package. Cmder is able to load now.

**Comment by LuigiLazzari** [comment] 2015-07-21 13:25
I can't install the redistributable alone, I can't install the whole VS 2015, would like if Cmder came with the necessary dlls

**Comment by gmsantosxl** [comment] 2015-07-21 16:19
Check the previous issues, the VC++ redist 2015 link was already posted:

https://www.microsoft.com/en-us/download/details.aspx?id=46881

**Comment by LuigiLazzari** [comment] 2015-07-21 19:05
I just said I can't install it, it keeps throwing an error, that's why  asked for the dlls to be included on the release files.

**Comment by jmparis** [comment] 2015-07-22 10:59
Just to inform that, I've installed on a PC N°1 the VS 2015 Community edition, and cmder 1.2 ran fine. BUT on the PC N°2 with VS 2015 Ultimate edition; i got the same error "the library was missing".

So, I've downloaded and installed on PC N°2 the latest VC 2015 package (x64) here:
http://download.microsoft.com/download/9/3/F/93FCF1E7-E6A4-478B-96E7-D4B285925B00/vc_redist.x64.exe
And everything ran fine.

Clearly, this missing library must be added to cmder

**Comment by abhinavk** [comment] 2015-07-24 08:30
The linked posted was of RC. I installed the one from Community ISO.

**Comment by SeeThruHead** [comment] 2015-07-24 19:32
Is this going to be fixed at any point? It's very off putting for a new user trying cmder for the first time. (VC++ redist - any version, fails to install)

**Comment by shoeper** [comment] 2015-07-28 13:39
Still getting this error with the new release.

**Comment by Stanzilla** [comment] 2015-07-28 15:12
The maintainers, @MartiUK and @bliker are both MIA. So that might take a while.

**Comment by shoeper** [comment] 2015-07-28 15:19
Ok.
But I can confirm that doing what gmsantosxl suggested did solve it for me.

**Comment by Stanzilla** [comment] 2015-07-28 15:49
Yeh, installing VC 2015 (both 32bit and 64bit on a 64bit system) is enough to make it work, the files are just missing from the zip.

**Comment by SeeThruHead** [comment] 2015-07-28 15:51
None of those links install on my 1 week old windows 7 64 install. fwiw. So I'm still out of luck.

**Comment by Stanzilla** [comment] 2015-07-28 15:56
@SeeThruHead Try http://www.microsoft.com/en-us/download/details.aspx?id=48145

**Comment by SeeThruHead** [comment] 2015-07-28 15:57
Have tried that multipled times. will not install. Is there a link to the files that I can put into the cmder folder?

**Comment by Stanzilla** [comment] 2015-07-28 16:04
No official ones, no. What does it say when it fails to install? Btw, the last cmder release has a lot of other problems, too so you might be better off using the last stable one https://github.com/bliker/cmder/releases/tag/v1.1.4.1 anyway.

**Comment by cfontes** [comment] 2015-08-03 12:58
Still broken

**Comment by Stanzilla** [comment] 2015-08-03 17:08
If someone feels adventures, one can test this https://github.com/Stanzilla/cmder/releases/tag/v1.2.1

It should work without any DLLs as is.

**Comment by catdad** [comment] 2015-08-03 23:58
@Stanzilla v1.2.1 works for me without the DLLs.

v1.2.0 did not work, even on a machine with the right redistributable installed, but you mentioned that one has a lot of problems.

Any ETA on when v1.2.1 is going to become the latest?

**Comment by catdad** [comment] 2015-08-03 23:59
Duplicate of 537

**Comment by Stanzilla** [comment] 2015-08-04 03:57
@catdad it's my own fork, so probably never. but as soon as @MartiUK comes back he can apply what I did to the main project.

**Comment by catdad** [comment] 2015-08-04 12:25
@Stanzilla I'm not sure what the culture is on this project, but I would submit a PR if I were you. I could not get any of the official builds working, even after installing all of the libs it complains about, but yours worked immediately on a fresh Windows install. I wouldn't let that work go to waste.

**Comment by MartiUK** [comment] 2015-08-04 12:38
PRs are encouraged @Stanzilla as long as your changes don't break everything there's no reason why.

**Comment by Stanzilla** [comment] 2015-08-04 12:55
Oh hey, you are alive!

**Comment by DanielGGordon** [comment] 2015-08-31 22:32
Hmm I downloaded the newest 1.2 build here: https://github.com/cmderdev/cmder/releases/tag/v1.2

And still I have this same error. Is that link for 1.2 not the updated build? I'm a bit new to using Github, so forgive me if I'm missing something really stupid.

**Comment by catdad** [comment] 2015-09-01 12:26
@DanielGGordon 1.2 is the latest official release. While a fix for this issue was proposed and merged into a development branch, it has not yet made it to an official release.

**Closed** 2015-10-12 11:20 UTC
