### ISSUE TITLE
Aliases do not work under Win10 1703 (Build 15063.11)

### ISSUE THREAD

**Issue by JoaoRodrigues** [cmderdev/cmder#1325] opened 2017-04-01 05:38 UTC
Hi all,

First of all, thanks for this amazing piece of software. It's making my life so easy when coming from MacOS..

I ran into trouble when updating to this newer build of Win 10. I am having problems with aliases **or** with launching the linux subsystem BASH shell.  My problems have been mentioned in #1306 and #1257. If I tick the 'use legacy mode' in cmd, I lose the ability to launch a BASH shell. If I do not, my aliases do not work. 

Does any one have any idea why this is happening, or a pointer to look for the root of the problem? Other aliases (e.g. ls, clear) work, so I am guessing it can be something with the loading of the alias file?

**Comment by Foxandxss** [comment] 2017-04-02 13:59
I use the `user-profile.sh` for my git-for-windows aliases and they don't work either.

**Comment by Foxandxss** [comment] 2017-04-02 14:02
On a fresh download of `cmder` it does work, but I lose stuff like having the branch name on the prompt. So I have to pick between one of those now.

If I update `git-for-windows` in the vendor. I get my branch name, I lose alias.

**Comment by AviVahl** [comment] 2017-04-03 19:16
Verified here, and very annoyed by it.

**Comment by daxgames** [comment] 2017-04-04 00:26
Windows insider build?

**Comment by AviVahl** [comment] 2017-04-04 00:38
Final stable Windows Creators Update... already released to insiders, yes, but will also be released to everyone else soon.

**Comment by daxgames** [comment] 2017-04-04 00:48
Aliases worked prior to a previous Windows insider update.  Not sure about this release as I am not running it.  Cmder aliases for the cmd shell are based on the very old doskey macro functionality.  We are somewhat at the mercy of Microsoft on this one if they break doskey then I don't know what we will do.  It is probably best to wait untill an official Windows release and try then to see if they fix it.

The question I have is do doskey macros work in standard window cmd prompt window outside cmder with similar settings?  If not it's not a cmder issue.

**Comment by Foxandxss** [comment] 2017-04-04 10:22
I use Windows insider version indeed.

I am using bash:bash with `git-for-windows`. I had to replace it with a new version because it wasn't working that well (e.g. no branch information in the prompt).

To get my alias back, I do a `source ~/path/to/cmder/config/user-profile.sh` but it is not ideal.

**Comment by jrappen** [comment] 2017-04-05 22:51
@daxgames Can reproduce this issue with the Creator's Update Assistant, which has been released today (April 5th) and ships Win10 Version 1703.

* Creator's Update Assistant: <https://go.microsoft.com/fwlink/?linkid=845981>
* <https://www.microsoft.com/en-us/software-download/windows10>
* <https://blogs.windows.com/windowsexperience/2017/03/30/managing-windows-10-creators-update-rollout-seamless-experience/>

**Comment by ingro** [comment] 2017-04-06 13:59
Same here with the update assistant.

**Comment by jrappen** [comment] 2017-04-07 08:04
`ls` and `clear` work fine for me as well, however `e.` and `cmderr` do not.

**Comment by phytemit** [comment] 2017-04-07 08:55
Confirmed. I'm running Windows 10 version from Update Assistant. For the aliases to start working again I needed to
![consoledefaults](https://cloud.githubusercontent.com/assets/1971302/24793035/b3996ea6-1b80-11e7-9b24-5762b7ec9815.png)

but this is of course not ideal.

**Comment by xupisco** [comment] 2017-04-07 14:18
Hi there, using legacy console works on cmd... but not with bash. :(

**Comment by mattdkerr** [comment] 2017-04-07 19:08
As monwf just linked, this is an issue with how Clink works in the new builds of Windows. What used to work now has a bug. Not sure which side needs fixes (possibly both). If you use ConEmu separately from cmder, without Clink, Doskey should work fine.

**Comment by JoaoRodrigues** [comment] 2017-04-07 21:06
@phytemit Yes, that is a workaround, but as I mentioned in the original post, then you cannot launch the BASH shell (WSL). 

The workaround mentioned in the thread linked by @MonwF ([link](https://github.com/mridgers/clink/issues/438#issuecomment-292156876)) could work but seems a bit cumbersome?

**Comment by bitcrazed** [comment] 2017-04-10 16:43
Hi. Microsoft PM for Bash/Console/Cmd here.

Thanks for looping us into the thread - will take a look and get back to y'all ASAP.

**Comment by bitcrazed** [comment] 2017-04-10 17:15
Update: We are tracking this issue internally (bug 11524988 for future reference). 

Also related to Clink issue 438: https://github.com/mridgers/clink/issues/438 

Bear with us while we work through the process.

**Comment by bannus** [comment] 2017-04-17 15:11
If you want to go with the [`.cmd` files for each alias workaround](https://github.com/mridgers/clink/issues/438#issuecomment-292156876), you can use [this powershell snippet] (https://github.com/mridgers/clink/issues/438#issuecomment-294504660).

**Comment by jrappen** [comment] 2017-04-19 08:02
@bitcrazed Do you have more info whether or not MSFT will fix this on their end, and maybe a timeframe?

**Comment by corstar** [comment] 2017-04-20 03:39
Glad to see this is a recent issue that people are working on. Looking forward to a working result.
Using win 10, creaters update here.

**Comment by J4r3tt** [comment] 2017-04-21 15:22
hope this issue can be fixed asap,thanks for hard working

**Comment by sabermylord** [comment] 2017-04-30 01:02
Yep, my version is 1703, i have the same promblem too :( Thats too bad and this problem makes me want to back to win7 :p

**Comment by bitcrazed** [comment] 2017-05-02 00:27
@corstar No ETA yet - we're currently slammed getting feature work completed for the next OS release. Will take a look when we move onto bugs in a couple of weeks.

**Comment by jrappen** [comment] 2017-05-02 08:29
@bitcrazed So that means MSFT won't be fixing this in a patch via Windows Update and we should use work-arounds until a major release in October or even April next year?

**Comment by AviVahl** [comment] 2017-05-02 10:50
@bitcrazed we'll be able to give you instant feedback if a fix lands in an Insider build or a KB fix.
Thanks for the update! Much appreciated.

**Comment by philgs** [comment] 2017-05-17 10:31
Using @phytemit's work-around is effective for me with the exception of "nested" alias. For example, my old aliases included `ls=ls --show-control-chars -F --color $*` and `ll=ls -al`. After enabling the legacy console, doing `ll` did not pick up the `--color` option defined on the "ls" alias. It's easy enough to fix by updating "ll" to `ll=ls --show-control-chars -F --color -alh $*`. 

Just thought I'd mention it in case someone gets stuck! 😺

**Comment by nonsocode** [comment] 2017-06-23 09:52
Mine started working again this morning. When i opened cmder I got this message
```
Clink v0.4.8 [git:d565ad] Copyright (c) 2012-2016 Martin Ridgers
http://mridgers.github.io/clink
```
Now all aliases seem to be working just fine and i can also use `bash` in cmder

**Comment by Foxandxss** [comment] 2017-06-23 09:53
Not for me. Perhaps I broke it while trying stuff.

Let's see what other people say.

**Comment by Gelio** [comment] 2017-06-23 10:26
It doesn't work for me either. I didn't get that message. Upon opening Cmder I got the usual ssh-agent starting.

I don't see why it would start working now. Was there an Insiders Build Windows update? As far as I can tell there hasn't been an update for Cmder recently as well.

@nonsocode Did you do anything the previous day that would fix aliases?

**Comment by seancheung** [comment] 2017-07-06 01:13
This should be a temporary solution.
After enabling **legacy console support**, **Ubuntu on Windows** no longer works.

> Unsupported console settings. In order to use this feature the legacy console must be disabled.
> Press any key to continue...

**Comment by cmeza** [comment] 2017-07-26 16:11
I'm not using WSL & have thoroughly enjoyed working with cmder, so enable legacy console support for me it is using @phytemit fix.

**Comment by Aristona** [comment] 2017-08-15 08:26
I had problems with opening Console Properties, it was crashing after the update. If you need to change to legacy version, you can open regedit and go to HKEY_CURRENT_USER\Console.

Change the value of "ForceV2" to 00000000

**Comment by Justsoos** [comment] 2017-08-15 10:30
Same problems, I had to shift to Bash on linux on Win 10, more regular bash command environment, and real alias controlled by ~/.bashrc (Ubuntu bash). Seems the arrogance and abduction of M$ pushed us to that.

```
root@DESKTOP-PMQ6DR3:~# uname -a
Linux DESKTOP-PMQ6DR3 4.4.0-43-Microsoft #1-Microsoft Wed Dec 31 14:42:53 PST 2014 x86_64 x86_64 x86_64 GNU/Linux
```

and DO remember, if your ubuntu bash version is lower than 16.0, such as 14.04.5 LTS, it was totally out-of-date, you must update to 16.04 up, do not try to upgrade, there are bugs of M$, just uninstall with `lxrun /uninstall` then run `lxrun /install` to get the 16.04 up version.

```
root@DESKTOP-PMQ6DR3:~# lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.3 LTS
Release:        16.04
Codename:       xenial
```

**Comment by CraneJen** [comment] 2017-09-04 09:34
@phytemit  It worked!!

**Comment by Beej126** [comment] 2017-10-15 18:08
[linking to the Clink fix for this](https://github.com/mridgers/clink/pull/464)

**Comment by Justsoos** [comment] 2017-10-25 05:36
https://github.com/cmderdev/cmder/issues/1325#issuecomment-292480901 
change cmd of win 10 to legacy console mode will lead to broken of bash linux on win 10: 
**`Unsupported console settings. In order to use this feature the legacy console must be disabled.`**

**Comment by hzhu212** [comment] 2017-12-15 02:03
A new version of Cmder has been available : [Cmder Release](https://github.com/cmderdev/cmder/releases)

I was surprised to find that the `user-alias.cmd` could function normally again!

So, **No Need to Set CMD Legacy Mode Any More**

**Comment by jpotma** [comment] 2017-12-15 12:13
The new version (1.3.4) does fix the issue. just extract over your previous install folder and that fixed the issue for me.

**Closed** 2017-12-15 21:37 UTC

**Comment by necoli1822** [comment] 2018-04-17 06:59
Don`t know it is the case of yours, but in my case, the whole wsl colour theme gone after writing ".bash_profile" in the root folder.
After I removed ".bash_profile", the color of [user@machine] and also color theme of commend 'ls' recovered.

**Comment by bitcrazed** [comment] 2018-04-17 16:40
`~/.bash_profile` loads `~/.profile` which loads `~/.bashrc` which is where your bash colors etc. are configured.

So if you overwrite `~/.bash_profile`, you'll prevent the above from happening and your color settings won't be loaded & applied.
