### ISSUE TITLE
cmder is extremely slow

### ISSUE THREAD

**Issue by arieljannai** [cmderdev/cmder#763] opened 2015-12-10 04:54 UTC
Hi,

Cmder is very slow (I don't know if it's only me or not, I guess not).
- It takes about **6** seconds to open a new tab (cmd/powershell with the injections)
- **1.5-2** seconds to get output after pressing enter (even if it was an empty command. just pressing enter)
- The thing that takes most of the time from what I've seen, is the process of what `cmder.lua` does. Without it it takes significant less time to do simple operations (still not speedy as regular cmd or cygwin, but reasonable).
- I didn't pass through the script to see what it does (except setting some settings) but another thing that happens is that when I press enter I can see the tab name changing to `git.exe` and going back to `cmd.exe` afterwards. This process which I don't know yet why it's happening also slows it down a lot.

Hope those are things that can be fixed!

Please tell me if there's something I can check to help with that. It's a great tool and it's frustrating that I can't use it.

Thanks! :sunny: 
Ariel

<BR><BR>
_If needed, I can record my screen while doing simple actions to demonstrate it_ :video_camera: :computer:

**Comment by kevinclcn** [comment] 2015-12-12 02:54
It is same for me. That should caused by git. How can I disable the git prompt plugin?

**Comment by kevinclcn** [comment] 2015-12-12 03:06
I just replace below line with `return false` to speed up.
https://github.com/cmderdev/cmder/blob/master/config/cmder.lua#L61

**Comment by arieljannai** [comment] 2015-12-12 13:25
didn't helped :cry:

**Comment by mynkow** [comment] 2015-12-16 11:46
I also have extremely slow cmder but only when I connect trough remote desktop. The host machine is Windows 7 enterprise. KBD input takes 4-5 seconds per character. Opening cmder takes more than 6 seconds. All other console windows (cmd, bash, PS) are OK

On my local machine with windows 10 it is ok trough remote desktop.

How can I help to fix this?

**Comment by niwox** [comment] 2015-12-17 11:21
Cmder is insanely slow for me too since the update !

**Comment by arieljannai** [comment] 2015-12-26 18:24
on my personal computer (windows 10) it's extremely slow, but on my work computer (windows 7) it's pretty fine.

**Comment by arieljannai** [comment] 2015-12-26 18:24
@bliker any idea?

**Comment by LordNoteworthy** [comment] 2015-12-27 15:08
same here  !

**Comment by luizbills** [comment] 2016-01-03 02:48
+1

**Comment by okaufmann** [comment] 2016-01-05 23:00
+1

**Comment by Manuzor** [comment] 2016-01-06 09:32
Same here!

**Comment by MartiUK** [comment] 2016-01-06 09:40
A lot of this is resolved in the CI builds, newer versions of completions in cmd and powershell are a lot faster.

I'm hoping to have a pre-release available soon.

**Comment by Manuzor** [comment] 2016-01-06 09:43
Awesome! Looking forward to it! :+1:

**Comment by Bartimoot** [comment] 2016-01-06 12:57
If it can help, running cmder as admin seems to solve the problem on my computer. (At least it isn't as slow..)

**Comment by superzadeh** [comment] 2016-01-13 13:16
+1, same issue. It does not happens 100% of times though, sometimes restarting cmder fixes the problem.

**Comment by tribet84** [comment] 2016-02-02 21:13
+1

**Comment by enriquein** [comment] 2016-02-26 21:24
This happens to me usually when I launch cmder with a split panel configuration. Most of the times one of the panels will be fine and the other would be really slow to react to input. Agree that it usually works itself out if I close cmder and try opening it again.

**Comment by sekai92id** [comment] 2016-03-31 16:45
+1

**Comment by TaylorHuston** [comment] 2016-04-06 01:30
This happens to em intermittently as well. Cmder is great 90% of the time, but occasionally (eventually?) it slows down to an insane crawl. A reboot is always needed to fix it.

**Comment by SCLeoX** [comment] 2016-04-07 22:51
No fair...... I get i7 process and 16GB memory with 0s cmd start up time......

It takes me more than 40 seconds to start cmder in a non git directory. I have no idea why it is soooooooo slow.

**Comment by gustavohenke** [comment] 2016-04-07 23:47
As a hint for anyone here:
I took the latest [v1.3.0-pre](https://github.com/cmderdev/cmder/releases/tag/v1.3.0-pre) tag, and it's almost real time for me if compared to the previous [v1.2.9](https://github.com/cmderdev/cmder/releases/tag/v1.2.9) release (which used to take 5 seconds every command).

**Comment by daxgames** [comment] 2016-04-07 23:53
I have been using 1.3.0 pre for a long time and every now and then vim freaks out and hogs 98% cpu.  Only way to recover is to kill vim.exe. No idea why but I have not really tried to figure it out.

**Comment by kdeenanauth** [comment] 2016-04-13 19:43
+1

**Comment by arieljannai** [comment] 2016-04-15 16:27
I tried a few more times to reinstall cmder, now I'm with 1.3 pre and it's pretty much fine compared to what I had before. On 1.2 I encountered the most slowness in git folders (not that others were fast..).

Anyway, I still think it can be better, the problem is that I don't know what affects the slowness of cmder, maybe it's some settings, another programs etc.

_**If you also have this problem, react with :+1: on the issue itself**, that way not all of the participants will get notifications for every +1 comment!_

**Comment by delscorcho** [comment] 2016-05-05 15:46
Any word on this?  Starting a new PowerShell cmd window takes nearly a minute. It's unusable.

**Comment by Stanzilla** [comment] 2016-05-05 20:07
@delscorcho which version of cmder are you on?

**Comment by delscorcho** [comment] 2016-05-05 20:26
1.2.9. It's a lot better with the 1.3.0 pre-release.

**Comment by centur** [comment] 2016-05-13 02:08
I'd like to add small hint to this thread ( and it might be a good idea to add this to the vendor/profile.ps1)
My Posh startup time goes bad beyond imagination (1.3.0 pre with few Azure modules installed takes from 3 to 12 seconds per console start) and after some research I found that [this advice from SO](http://stackoverflow.com/questions/4208694/how-to-speed-up-startup-of-powershell-in-the-4-0-environment) is still valid, even for v5. Crazy but fact, start time plummeted down to 1-2 seconds per console start (and profile.ps1 boot time for Powershell is 0.2 secs with posh-git disabled)

**Comment by sebastianpennino** [comment] 2016-05-20 14:46
Thanks @SCLeoX If I start my cmder on a git folder the problem is solved (i'm using cmder v1.2.9)

**Comment by arieljannai** [comment] 2016-05-26 21:04
@centur which of the answers there were useful for you?

**Comment by centur** [comment] 2016-05-27 03:00
@arieljannai oh, I didn't realized I referenced to the question, not to the answer. 

["Run NGEN on Posh binaries."](http://stackoverflow.com/questions/4208694/how-to-speed-up-startup-of-powershell-in-the-4-0-environment/22920915#22920915) is useful, I have it in my profile script for admin prompt.
I also double-checked and re-enabled scheduler for NGENing my assemblies.

**Comment by ryannewton** [comment] 2016-06-27 13:57
It' still running slow for me. Is anyone else still having this issue?

**Comment by Stanzilla** [comment] 2016-06-27 16:13
Post your git, clink and conemu versions pls.

**Comment by ryannewton** [comment] 2016-06-27 21:51
I'm new to this, where can I find the git, clink, and conemu versions?
In the cmder folder there's a file named Version v1.2.9

**Comment by Stanzilla** [comment] 2016-06-27 22:13
type `git --version` `clink` and `conemu -?´

**Comment by ryannewton** [comment] 2016-06-28 00:12
git version 2.8.0.windows.1
Clink v0.4.5
ConEmu version 160619 stable

**Comment by Stanzilla** [comment] 2016-06-28 00:57
Alright, can you download a test build from here and tell me if that works better, please. https://ci.appveyor.com/project/MartiUK/cmder/build/artifacts

**Comment by ryannewton** [comment] 2016-06-28 14:13
Wow, that's much better.
Thanks!

**Comment by SCLeoX** [comment] 2016-07-14 10:55
My version is 160710, problem does not disappear. It takes about 30 seconds to boot up. I can start cmd within 0.5 sec.

**Comment by Stanzilla** [comment] 2016-07-14 10:59
@SCLeoX install https://github.com/cmderdev/cmder/releases/tag/v1.3.0

**Comment by g0ld3lux** [comment] 2016-11-20 17:06
i think the culprit is the function 

get_git_status()
```
function get_git_status()
    local file = io.popen("git status --no-lock-index --porcelain 2>nul")
    for line in file:lines() do
        file:close()
        return false
    end
    file:close()
    return true
end
```
I read that it will takes up so much time 
https://gist.github.com/sindresorhus/3898739#gistcomment-1897703
and the fastest is this one ... it makes a lot faster :)
```
function get_git_status()
    return os.execute("git diff-files --no-ext-diff --quiet")
end
```

**Comment by Stanzilla** [comment] 2016-11-20 17:42
Wouldn't `git diff-files --no-ext-diff --quiet || git diff-index --no-ext-diff --quiet --cached HEAD` be better than since we probably want indexed and unindexed?

**Comment by shahril96** [comment] 2016-11-28 10:44
For those who want to disable the Git checking, then see here : https://github.com/cmderdev/cmder/issues/447#issuecomment-244149494

**Comment by Oxicode** [comment] 2016-11-28 15:00
:+1:

**Closed** 2017-11-25 00:27 UTC
Labels: Outdated Installation

**Comment by THCloud** [comment] 2018-01-08 08:10
I use 161206 stable
ssh to some remote machine， open a vim, and :vsp 
then move the cursor
...... really really really slow

**Comment by petermeiller** [comment] 2018-02-06 14:42
My git was very very slow
I had a network share as my home directory, I changed that but it only incrementally helped
I also tried the settings about file cache, that did not help me
what helped me was uninstalling 1.8 32 bit and installing 2.2 64 bit
I am on windows 7

**Comment by Oxicode** [comment] 2018-03-15 19:31
+1 very slow in where.exe

**Comment by MartiUK** [comment] 2018-03-15 19:38
Can you confirm after whitelisting the exes in your antivirus?

**Comment by EdZava** [comment] 2018-12-14 13:54
I have the same problem opening the cmder in a large project that has git.

It is very slow, it can reach more than 2 minutes to load.

I have the latest version: v1.3.10

Is there any solution to this issue?

**Comment by wisehuang** [comment] 2019-02-22 10:33
temperory solution:
comment these codes in local function git_prompt_filter() in clink.lua under cmder\vendor folder:
```local git_dir = get_git_dir()
    if git_dir then
        -- if we're inside of git repo then try to detect current branch
        local branch = get_git_branch(git_dir)
        local color
        if branch then
            -- Has branch => therefore it is a git folder, now figure out status
            local gitStatus = get_git_status()
            local gitConflict = get_git_conflict()

            color = colors.dirty
            if gitStatus then
                color = colors.clean
            end

            if gitConflict then
                color = colors.conflict
            end 

            clink.prompt.value = string.gsub(clink.prompt.value, "{git}", color.."("..branch..")")
            return false
        end
    end```

then cmder will not try to get git status in git folder

**Comment by fslayer** [comment] 2019-05-10 14:40
Still extremely slow.

**Comment by daxgames** [comment] 2019-05-10 17:10
@fslayer in what way.  I have not seen any slowness beyond some at initial startup.  You can add the `/f` command line switch to the Conemu task that starts the session.  This is only applicable for `cmder::cmder *` sessions.  This will take 2-3 seconds off of initial startup of Cmder.

Also what sessions are slow cmd, bash, or powershell.

**Comment by S1d0** [comment] 2019-06-04 11:26
Also for me it works really - my version 1.3.11.843. It tooks ages to startup also moving from one dir to other take really long. Looking forward for solutions...

**Comment by Kogam22** [comment] 2019-06-09 02:36
I read somewhere(Google how to speed up WSL) Windows Defender affects the speeds of WSL very very much. You can get 5x speed on WSL I/O and other operations by disabling it. Maybe disabling it will also help Cmder.

**Comment by jpruiz114** [comment] 2019-06-25 19:19
This ticket is closed but seems like this is still happening, at least for me it happens on a daily basis, super slow to open new tabs and to perform simple things such as an ls.

**Comment by fslayer** [comment] 2019-06-25 19:44
I solve the problem. I just installed Linux and... problem solved!! :)

**Comment by therepo90** [comment] 2019-07-03 07:56
Same  here

**Comment by davidnero** [comment] 2019-07-07 20:06
I'm seeing extreme slowness as well.

**Comment by davidreza** [comment] 2019-07-25 04:58
Smae issue here on a high-end laptop; in 2019

**Comment by davidnero** [comment] 2019-07-25 15:06
In my case, the slowness was caused by my laptop looking for my employer's domain when I was at home. It seems to be some kind of windows terribleness where the domain lookup has to timeout before cmder (or maybe the underlying msys?) can run anything.

I found a work-around here: [](http://bjg.io/guide/cygwin-ad/)

**Comment by MyrionSC** [comment] 2020-05-15 09:32
Turning off Windows Defender helped a lot for me.

**Comment by SymonBlazejczakPXL** [comment] 2020-10-02 19:59
Deleting System98 helped a lot for me.

**Comment by doglex** [comment] 2020-12-24 14:14
just remove those function calls , and hard code all env, since you know the very git_install location. 
My demo,  https://github.com/doglex/Light_Weapon/blob/master/cmder/vendor/init.bat

which is fast
0.5s in HDD
0.1s in SSD

**Comment by blowsie** [comment] 2021-02-04 11:47
I disabled the git as mentioned in one of the comments, cmder still taking 16 seconds to load

**Comment by aleksandarbos** [comment] 2023-05-28 18:41
having it integrated with vscode, switching from branch to branch or writing a simple commit message is suuuper slow, any ideas on how to solve this?

**Comment by chrisant996** [comment] 2023-05-29 00:07
Possibly is caused by anti-malware. Do you use ESET? For example, ESET has been having performance problems lately with ConEmu. If so, you can probably confirm by turning off "Deep Behavioral Inspection" in ESET.

**Comment by aleksandarbos** [comment] 2023-05-29 13:18
> Possibly is caused by anti-malware. Do you use ESET? For example, ESET has been having performance problems lately with ConEmu. If so, you can probably confirm by turning off "Deep Behavioral Inspection" in ESET.

hey, thanks for the reply. nope, just use standard win 10, no any custom anti-virus software installed - it uses standard win10 protection.

**Comment by daxgames** [comment] 2023-05-29 14:10
@aleksandarbos I assume you are using git?  How big is the git repo?  Is the speed consistent across all git repos?

Is this a fresh cmder install or have you updated an old install over the years?  Try a fresh install.

**Comment by aleksandarbos** [comment] 2023-05-29 15:57
big thanks @daxgames it's fixed!

`prompt_overrideGitStatusOptIn = true` did the trick.

i've noticed it's git related, each time for example if i'd start typing something in cmder, vs code would start refreshing git state.
![image](https://github.com/cmderdev/cmder/assets/15141614/c275cf58-5846-4ff5-a404-246893bb3e07)

repo size is moderate i guess.

i just recently downloaded new version hoping it will fix it, and i'm on `Version 1.3.20.151`.

**Comment by daxgames** [comment] 2023-05-29 16:18
@aleksandarbos Glad to help

**Comment by chrisant996** [comment] 2023-05-29 21:53
> i just recently downloaded new version hoping it will fix it, and i'm on `Version 1.3.20.151`.

What version of Cmder were you using before?

v1.3.20 includes improvements that make the git prompt be updated completely in the background; there should be zero delay from git anymore.

**Comment by aleksandarbos** [comment] 2023-05-30 10:08
> > i just recently downloaded new version hoping it will fix it, and i'm on `Version 1.3.20.151`.
> 
> What version of Cmder were you using before?
> 
> v1.3.20 includes improvements that make the git prompt be updated completely in the background; there should be zero delay from git anymore.

prev version was `1.3.18.1106`. not sure why but i got rid of git delay only after setting `prompt_overrideGitStatusOptIn = true`.

**Comment by chrisant996** [comment] 2023-05-30 15:22
> prev version was `1.3.18.1106`. not sure why but i got rid of git delay only after setting `prompt_overrideGitStatusOptIn = true`.

Setting that completely disables the git status in the prompt.

But you also upgraded to 1.3.20, and you no longer need to set that:  1.3.20 fixed the git slowness.

**Comment by daxgames** [comment] 2023-05-30 16:33
@chrisant996 this is the description of that setting and why I recommended it to him

```
-- OPTIONAL. If true then always ignore the cmder.status and cmder.cmdstatus git config settings and run the git prompt commands in the background. -- default is false -- NOTE: This only takes effect if using Clink v1.2.10 or higher. 
```

**Comment by chrisant996** [comment] 2023-05-30 17:11
@aleksandarbos was using v1.3.18.  That doesn't know about `prompt_overrideGitStatusOptIn`.  In v1.3.18 the prompt is slow because it runs git commands in the foreground and waits for them to complete.

Upgrading to v1.3.20 is mainly what fixed the slowness.

@daxgames I misremembered how that works.  I looked it up, and here is how it works:

Once upgraded to v1.3.19 or v1.3.20, then `prompt_overrideGitStatusOptIn = true` can work around an issue where the `git config` command was still being run in the foreground, which could still add some delay between command prompts.

v1.3.21 (not yet released) fixes that by moving `git config` into the background as well.

In v1.3.21 and higher, setting `prompt_overrideGitStatusOptIn = true` will not reduce the delay between command prompts (there shouldn't be _any_ delay anymore), but it can potentially make the status info get refreshed sooner after the new prompt is displayed, since it skips even the background `git config` calls.

**Comment by aleksandarbos** [comment] 2023-07-06 11:48
@chrisant996 after some more testing, it seems to be only the issue with the integrated cmder instance within the vscode. launching cmder in a separate window, everything works fine.

**Comment by aleksandarbos** [comment] 2023-07-06 14:25
`where cmder` points to the same distribution in both vscode integrated and non-integrated case `Version 1.3.20.151`. it seemed like it worked faster after updating the config, but looks like something is still holding off. i've clipped gif, it took almost 2 min to execute what i was writing. note that i wrote the sentence and waited for the whole time just to print it out
![cmder](https://github.com/cmderdev/cmder/assets/15141614/74d0ced3-4a82-4578-b4d8-6c2769bc3094)

**Comment by chrisant996** [comment] 2023-07-06 14:31
@aleksandarbos Thank you for clarifying where you're seeing slowness. That is very different from the slowness we were talking about _between_ prompts. You're experiencing slowness _while typing input_.

I've never heard of that before.

I can try to take a look.  If you happen to have instructions for how to set up Cmder integrated inside vscode, can you share a link?

**Comment by aleksandarbos** [comment] 2023-07-06 14:38
think this one should do, https://github.com/cmderdev/cmder/wiki/Seamless-VS-Code-Integration. this is my config:
```
"terminal.integrated.profiles.windows": {
    "Cmder": {
      "path": [
        "${env:windir}\\Sysnative\\cmd.exe",
        "${env:windir}\\System32\\cmd.exe"
      ],
      "env": { "CMDER_ROOT": "E:\\tools\\cmder" },
      "args": ["/K", "%CMDER_ROOT%\\vendor\\bin\\vscode_init.cmd"],
      "icon": "cmder"
    }
  },
  "terminal.integrated.defaultProfile.windows": "Cmder",
  "terminal.integrated.allowChords": false,
  "terminal.integrated.drawBoldTextInBrightColors": false,
  "terminal.integrated.experimentalLinkProvider": false,
  "terminal.integrated.rendererType": "auto",
  ```
  
think that i was trying to solve this issue before, it had something to do with `  "terminal.integrated.rendererType": "auto"` but not quite sure.

**Comment by chrisant996** [comment] 2023-07-06 15:27
@aleksandarbos The `...rendererType` setting was replaced by `terminal.integrated.gpuAcceleration`.  See [here](https://code.visualstudio.com/docs/terminal/basics#_im-having-problems-with-the-terminal-rendering-what-can-i-do).  Does changing the `...gpuAcceleration` setting in vscode to `"off"` make a difference?  Have you tried updating your video drivers?

Also, when using git outside vscode, how long does manually running `git status` take in that repo?

Is that repo publicly available?  I.e. can I clone it so that I have a repo where git status is slow?  None of the repos on my home machine take longer than 1 second to run `git status`.

**Comment by aleksandarbos** [comment] 2023-07-08 11:34
looks like switching `"terminal.integrated.gpuAcceleration": "off"` made things way better in my case. big thanks for the help @chrisant996
