### ISSUE TITLE
Can't see some fonts on output

### ISSUE THREAD

**Issue by worthwhileindustries** [cmderdev/cmder#1300] opened 2017-03-10 01:58 UTC
Windows 10 | cmder version 1.3.2

1) opened via cmder powershell with admin as administrator
2) choco install yarn
3) went back to standard cmd via cmder

and now i get this... tried changing colors and blowing away cmder but, the colors still persist. Does anyone have any idea what could have happened and how to get back to normal? I change the background to a bunch of different colors but, no luck. I can highlight the text and it shows up highlighted.

![cant-see-font](https://cloud.githubusercontent.com/assets/3536254/23778873/1f09fe6e-04fa-11e7-90f9-054eb8a54faa.JPG)

**Comment by JaneDawson** [comment] 2017-07-13 10:53
I had the same error. Found a workaround:
https://github.com/cmderdev/cmder/issues/1346

**Comment by sandropoluan** [comment] 2017-12-27 13:10
+1

**Comment by Stanzilla** [comment] 2017-12-28 13:04
Duplicate of https://github.com/cmderdev/cmder/issues/1346

**Closed by Stanzilla** 2017-12-28 13:04 UTC
