### ISSUE TITLE
Startup directory doesn't work

### ISSUE THREAD

**Issue by thany** [cmderdev/cmder#1303] opened 2017-03-13 10:20 UTC
When I've got a Cmder window open, and right-click in the tab bar to select *New console*, the startup directory chosen in the dialog that appears isn't respected. It **always** starts in my home directory (`C:\Users\username`) no matter what options I choose. It also doesn't matter if I do this from an elevated Cmder or not.

I've updated literally minutes ago, so everything should be up-to-date.
Cmder version 1.3.2
ConEmu version 161206
Windows 10 x64

**Comment by kibbled** [comment] 2017-03-23 15:01
Same here on Windows 7. Also if I close the second tab it crashes Cmder but not if I close the first tab after opening a second. Running latest build 161206 64-bit stable

**Comment by ZenToad** [comment] 2017-04-29 13:14
Same problem here.  Windows 10

**Comment by Saturate** [comment] 2017-06-14 12:17
Some issue for me

**Comment by thany** [comment] 2017-06-15 07:58
Looks like the issue is in the software then, not in the user 🙂

**Comment by angly-cat** [comment] 2017-09-30 08:54
TL;DR: delete `:d:%USERPROFILE%` from cmder task's command.

Actually, it works as intended. And by that I mean that new Cmder actually starts within specified "Startup directory for new process" and **then** it's working directory gets changed to whatever else.

So, in a task's command that starts cmder you can see something like `-new_console:d:"%USERPROFILE%"`. According to [`-new_console` syntax](https://conemu.github.io/en/NewConsole.html#syntax), `d` flag is for changing working directory. So, for that command to not change directory just remove that switch and this issue will be fixed for you.

**Comment by thany** [comment] 2017-10-02 08:36
I haven't added that to the command, so whatever the bug exactly is, is caused by default behaviour. Ergo, it still needs a fix and the suggestion you provide is merely a workaround.

And with al ldue respect, "it works as intended" in my mind reads as "it is intended wrongly" ;)

**Closed** 2017-10-28 12:21 UTC

**Comment by thany** [comment] 2017-11-15 09:34
Can I ask why this issue is closed? Has it been resolved in any way?

**Comment by angly-cat** [comment] 2017-11-15 09:59
It has been in #1504, as you can see right above your message.

**Comment by drunkwretch** [comment] 2018-08-24 07:27
@angly-cat  thx  save me
